<a href="https://colab.research.google.com/github/mohammadRahimi1993/BigData/blob/main/CheckGAFineTune.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#%tensorflow_version 1.x
!pip install ampligraph;
!pip install tensorflow==1.15.2;  
!pip install ypstruct;
import numpy as np;
import pandas as pd;
import ampligraph;
import numpy as np
import matplotlib.pyplot as plt
from ypstruct import structure
import numpy as np;
import pandas as pd;
import ampligraph;

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 168 kB 5.3 MB/s 
     |████████████████████████████████| 6.4 MB 14.7 MB/s 
     |████████████████████████████████| 482 kB 46.7 MB/s 
     |████████████████████████████████| 64 kB 2.5 MB/s 
     |████████████████████████████████| 2.7 MB 51.2 MB/s 
     |████████████████████████████████| 120 kB 21.0 MB/s 
     |████████████████████████████████| 561 kB 53.2 MB/s 
     |████████████████████████████████| 42 kB 808 kB/s 
     |████████████████████████████████| 69 kB 8.1 MB/s 
     |████████████████████████████████| 41 kB 600 kB/s 
     |████████████████████████████████| 90 kB 9.3 MB/s 
     |████████████████████████████████| 84 kB 3.4 MB/s 
     |████████████████████████████████| 121 kB 16.8 MB/s 
     |████████████████████████████████| 100 kB 7.4 MB/s 
  Created wheel for commonmark: filename=CommonMark-0.5.4-py3-none-any.whl size=30768 sha256=010d61113c

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 110.5 MB 35 kB/s 
     |████████████████████████████████| 503 kB 57.4 MB/s 
     |████████████████████████████████| 3.8 MB 40.9 MB/s 
     |████████████████████████████████| 50 kB 5.9 MB/s 
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7554 sha256=df1f74a1a0c702f65e59e8c86a9165a8ec89030129eabd5570594131b7c0cc50
  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
Successfully built gast
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 4.2.0
    Uninstalling importlib-metadata-4.2.0:
      Successfully uninstalled importlib-metadata-4.2.0
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-est

In [ ]:
def dataPreparing():
#def costFunction():
    from ampligraph.evaluation import train_test_split_no_unseen  
    import requests
    url = 'https://ampligraph.s3-eu-west-1.amazonaws.com/datasets/football_graph.csv'
    open('football_results.csv', 'wb').write(requests.get(url).content)
    df = pd.read_csv("football_results.csv").sort_values("date")
    print(df.isna().sum())
    df = df.dropna()
    df["train"] = df.date < "2014-01-01"
    print(df.train.value_counts())
        # Entities naming
    df["match_id"] = df.index.values.astype(str)
    df["match_id"] =  "Match" + df.match_id
    df["city_id"] = "City" + df.city.str.title().str.replace(" ", "")
    df["country_id"] = "Country" + df.country.str.title().str.replace(" ", "")
    df["home_team_id"] = "Team" + df.home_team.str.title().str.replace(" ", "")
    df["away_team_id"] = "Team" + df.away_team.str.title().str.replace(" ", "")
    df["tournament_id"] = "Tournament" + df.tournament.str.title().str.replace(" ", "")
    df["neutral"] = df.neutral.astype(str)
    
    triples = []
    for _, row in df[df["train"]].iterrows():
        # Home and away information
        home_team = (row["home_team_id"], "isHomeTeamIn", row["match_id"])
        away_team = (row["away_team_id"], "isAwayTeamIn", row["match_id"])
    
        # Match results
        if row["home_score"] > row["away_score"]:
            score_home = (row["home_team_id"], "winnerOf", row["match_id"])
            score_away = (row["away_team_id"], "loserOf", row["match_id"])
        elif row["home_score"] < row["away_score"]:
            score_away = (row["away_team_id"], "winnerOf", row["match_id"])
            score_home = (row["home_team_id"], "loserOf", row["match_id"])
        else:
            score_home = (row["home_team_id"], "draws", row["match_id"])
            score_away = (row["away_team_id"], "draws", row["match_id"])
        home_score = (row["match_id"], "homeScores", np.clip(int(row["home_score"]), 0, 5))
        away_score = (row["match_id"], "awayScores", np.clip(int(row["away_score"]), 0, 5))
    
        # Match characteristics
        tournament = (row["match_id"], "inTournament", row["tournament_id"])
        city = (row["match_id"], "inCity", row["city_id"])
        country = (row["match_id"], "inCountry", row["country_id"])
        neutral = (row["match_id"], "isNeutral", row["neutral"])
        year = (row["match_id"], "atYear", row["date"][:4])
    
        triples.extend((home_team, away_team, score_home, score_away, 
                        tournament, city, country, neutral, year, home_score, away_score))
    triples_df = pd.DataFrame(triples, columns=["subject", "predicate", "object"])
    triples_df[(triples_df.subject=="Match3129") | (triples_df.object=="Match3129")]
    
    X_train, X_valid = train_test_split_no_unseen(np.array(triples), test_size=10000)
    print('Train set size: ', X_train.shape)
    print('Test set size: ', X_valid.shape)
    return X_train, X_valid

In [ ]:
X_train, X_valid=dataPreparing()

date          0
home_team     0
away_team     0
home_score    2
away_score    2
tournament    0
city          0
country       0
neutral       0
dtype: int64
True     35714
False     5057
Name: train, dtype: int64
Train set size:  (382854, 3)
Test set size:  (10000, 3)


In [ ]:
def costFunction(X, X_train, X_valid):
    from ampligraph.latent_features import ComplEx
    model = ComplEx(batches_count=int(X[0]),
                    epochs=10,
                    k=int(X[2]),
                    eta=int(X[1]),
                    optimizer='adam', 
                    optimizer_params={'lr':1e-4},
                    loss='multiclass_nll',
                    regularizer='LP', 
                    regularizer_params={'p':3, 'lambda':1e-5}, 
                    seed=0, 
                    verbose=True)
    import tensorflow as tf
    tf.logging.set_verbosity(tf.logging.ERROR)
    # model.fit(X_train)
    model.fit(X_train[:10000,:10000])
    filter_triples = np.concatenate((X_train, X_valid))
    from ampligraph.evaluation import evaluate_performance
    ranks = evaluate_performance(X_valid[:100,:200],
                                 model=model, 
                                 filter_triples=filter_triples,
                                 use_default_protocol=True,
                                 verbose=True)
    #ranks = evaluate_performance(X_valid,
    #                             model=model, 
    #                             filter_triples=filter_triples,
    #                             use_default_protocol=True,
    #                             verbose=True)
    
    from ampligraph.evaluation import mr_score, mrr_score, hits_at_n_score

    mr = mr_score(ranks)
    mrr = mrr_score(ranks)

    print("MRR: %.2f" % (mrr))
    print("MR: %.2f" % (mr))

    hits_10 = hits_at_n_score(ranks, n=10)
    print("Hits@10: %.2f" % (hits_10))
    hits_3 = hits_at_n_score(ranks, n=3)
    print("Hits@3: %.2f" % (hits_3))
    hits_1 = hits_at_n_score(ranks, n=1)
    print("Hits@1: %.2f" % (hits_1))
    return float(mrr)


In [ ]:
def crossover(p1, p2, gamma=0.1):
    c1 = p1.deepcopy()
    c2 = p1.deepcopy()
    alpha = np.random.uniform(-gamma, 1+gamma, *c1.position.shape)
    print('alpha:', alpha)
    c1.position = alpha*p1.position + (1-alpha)*p2.position
    print('alpha*p1.position:', alpha*p1.position)
    print('(1-alpha)*p2.position',(1-alpha)*p2.position)
    c2.position = alpha*p2.position + (1-alpha)*p1.position
    print('alpha*p1.position:', alpha*p2.position)
    print('(1-alpha)*p2.position',(1-alpha)*p1.position)
    return c1, c2

def mutate(x, mu, sigma):
    y = x.deepcopy()
    flag = np.random.rand(*x.position.shape) <= mu
    ind = np.argwhere(flag)
    y.position[ind] += sigma*np.random.randn(*ind.shape)
    return y

def apply_bound(x, varmin, varmax):
    x.position = np.maximum(x.position, varmin)
    x.position = np.minimum(x.position, varmax)

def roulette_wheel_selection(p):
    c = np.cumsum(p)
    r = sum(p)*np.random.rand()
    ind = np.argwhere(r <= c)
    return ind[0][0]


In [ ]:
# Problem Definition
problem = structure()
problem.costFunc = costFunction
problem.nvar = 3
#X[0]:Batch ,X[1]:Iteration ,X[2]:Dimention Of Embbeding
problem.varmin = [100,20, 30]
problem.varmax = [ 300,200, 400]

# GA Parameters
params = structure()
params.maxit = 10
params.npop = 3
params.beta = 1
params.pc = 1
params.gamma = 0.1
params.mu = 0.9
params.sigma = 20

In [ ]:
# Problem Information
# costFunction = problem.costFunction
popc = []
nvar = problem.nvar
varmin = problem.varmin
varmax = problem.varmax

# Parameters
maxit = params.maxit
npop = params.npop
beta = params.beta
pc = params.pc
nc = int(np.round(pc*npop/2)*2)
gamma = params.gamma
mu = params.mu
sigma = params.sigma

# Empty Individual Template
empty_individual = structure()
empty_individual.position = None
empty_individual.cost = None

# Best Solution Ever Found
bestsol = empty_individual.deepcopy()
bestsol.cost = 0

pop = empty_individual.repeat(npop)
bestSolution = empty_individual.repeat(maxit)

# Initialize Population
for i in range(npop):
    pop[i].position = np.random.uniform(varmin, varmax, nvar) 
    print(pop[i].position)
for i in range(npop):
    print(pop[i].position)
    pop[i].cost = costFunction(pop[i].position, X_train, X_valid)
    print(pop[i].cost)
    if pop[i].cost > bestsol.cost:
        bestsol = pop[i].deepcopy()
    popc.append(pop[i])

# Best Cost of Iterations
bestposition = np.empty(maxit)
bestcost = np.empty(maxit)

# Main Loop
for it in range(maxit):
    costs = np.array([x.cost for x in pop])
    avg_cost = np.mean(costs)
    if avg_cost != 0:
        costs = costs/avg_cost
    probs = np.exp(-beta*costs)

    for _ in range(nc//2):

        # Select Parents
        #q = np.random.permutation(npop)
        #p1 = pop[q[0]]
        #p2 = pop[q[1]]

        # Perform Roulette Wheel Selection
        p1 = pop[roulette_wheel_selection(probs)]
        p2 = pop[roulette_wheel_selection(probs)]
        print('P1:', p1)
        print('P2:',p2)
  
        # Perform Crossover
        # c1, c2 = crossover(p1, p2, gamma)
        gamma = 0.01
        c1 = p1.deepcopy()
        c2 = p2.deepcopy()
        alpha = np.random.uniform(-gamma, 1+gamma, *c1.position.shape)
        c1.position = alpha*p1.position + (1-alpha)*p2.position
        c2.position = alpha*p2.position + (1-alpha)*p1.position
        apply_bound(c1, varmin, varmax)
        apply_bound(c2, varmin, varmax)

        # Evaluate First Offspring
        flag = False
        for element in popc:
          if (np.array_equal(element.position , c1.position)):
            print("Dynamic Programming")
            c1.cost = element.cost
            flag = True
            break;
        if (flag == False):
          print(c1.position) 
          c1.cost = costFunction(c1.position, X_train, X_valid)
          if c1.cost > bestsol.cost:
            bestsol = c1.deepcopy()

        # Evaluate Second Offspring
        flag = False
        for element in popc:
          if (np.array_equal(element.position , c2.position)):
            print("Dynamic Programming")
            c2.cost = element.cost
            flag = True
            break;
        if (flag == False):
          print(c2.position) 
          c2.cost = costFunction(c2.position, X_train, X_valid)
          if c2.cost > bestsol.cost:
            bestsol = c2.deepcopy()

        print('crossover c1:',c1)
        print('crossover c2:',c2) 

        # Perform Mutation
        c3 = c1.deepcopy()
        flag = np.random.rand(*c1.position.shape) <= mu
        ind = np.argwhere(flag)
        c3.position[ind] += sigma*np.random.randn(*ind.shape)
        #c1 = mutate(c1, mu, sigma)
        c4 = c2.deepcopy()
        flag = np.random.rand(*c2.position.shape) <= mu
        ind = np.argwhere(flag)
        c4.position[ind] += sigma*np.random.randn(*ind.shape)
        #c2 = mutate(c2, mu, sigma)
              
        # Apply Bounds
        apply_bound(c3, varmin, varmax)
        apply_bound(c4, varmin, varmax)

        # Evaluate Thirty Offspring
        flag = False
        for element in popc:
          if (np.array_equal(element.position , c3.position)):
            print("Dynamic Programming")
            c3.cost = element.cost
            flag = True
            break;
        if (flag == False):
          print(c3.position) 
          c3.cost = costFunction(c3.position, X_train, X_valid)
          if c3.cost > bestsol.cost:
            bestsol = c3.deepcopy()

        # Evaluate Fortith Offspring
        flag = False
        for element in popc:
          if (np.array_equal(element.position , c4.position)):
            print("Dynamic Programming")
            c4.cost = element.cost
            flag = True
            break;
        if (flag == False):
          print(c4.position) 
          c4.cost = costFunction(c4.position, X_train, X_valid)
          if c4.cost > bestsol.cost:
            bestsol = c4.deepcopy()

        print('mutate c3:',c3)
        print('mutate c4:',c4) 
        # Add Offsprings to popc

        popc.append(c1)
        popc.append(c2)
        popc.append(c3)
        popc.append(c4)
        
        # Check pop list for insert c1,c2,c3,c4
        flag = False
        for element in pop:
          flag = np.array_equal(element.position, c1.position)
          if flag == True:
            break
        if flag == False:
          pop.append(c1)
        
        flag = False
        for element in pop:
          flag = np.array_equal(element.position, c2.position)
          if flag == True:
            break
        if flag == False:
          pop.append(c2)

        flag = False
        for element in pop:
          flag = np.array_equal(element.position, c3.position)
          if flag == True:
            break
        if flag == False:
          pop.append(c3)

        flag = False
        for element in pop:
          flag = np.array_equal(element.position, c4.position)
          if flag == True:
            break
        if flag == False:
          pop.append(c4)


    # Merge, Sort and Select
    # pop += popc
    pop = sorted(pop, key=lambda x: x.cost, reverse=True)
    pop = pop[0:npop]
    print('pop:' , pop)
    
    # Store Best Cost
    bestcost[it] = bestsol.cost

    bestSolution[it].cost = bestsol.cost
    bestSolution[it].position = bestsol.position
                               
    # Show Iteration Information
    print("Iteration {}: Best Cost = {}".format(it, bestcost[it]))


# Output
out = structure()
out.pop = pop
out.bestsol = bestsol
out.bestcost = bestcost
print(out.pop)
print(out.bestsol)
print(out.bestcost)

[146.70868371 185.87978601 176.79842938]
[216.20987624 150.48667963 152.00108472]
[161.36298538 139.89529975 260.54421003]
[146.70868371 185.87978601 176.79842938]


Average ComplEx Loss:   5.126086: 100%|██████████| 10/10 [05:12<00:00, 31.28s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.69it/s]


MRR: 0.02
MR: 4430.33
Hits@10: 0.03
Hits@3: 0.03
Hits@1: 0.02
0.02451206242073298
[216.20987624 150.48667963 152.00108472]


Average ComplEx Loss:   4.838730: 100%|██████████| 10/10 [04:20<00:00, 26.09s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 13.02it/s]


MRR: 0.02
MR: 4947.10
Hits@10: 0.02
Hits@3: 0.02
Hits@1: 0.02
0.019360949866269173
[161.36298538 139.89529975 260.54421003]


Average ComplEx Loss:   4.768495: 100%|██████████| 10/10 [06:26<00:00, 38.61s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:03<00:00,  7.80it/s]


MRR: 0.02
MR: 3723.73
Hits@10: 0.07
Hits@3: 0.03
Hits@1: 0.00
0.023259429378882857
P1: struct({'position': array([146.70868371, 185.87978601, 176.79842938]), 'cost': 0.02451206242073298})
P2: struct({'position': array([146.70868371, 185.87978601, 176.79842938]), 'cost': 0.02451206242073298})
[146.70868371 185.87978601 176.79842938]


Average ComplEx Loss:   5.126086: 100%|██████████| 10/10 [04:53<00:00, 29.35s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 10.09it/s]


MRR: 0.02
MR: 4430.33
Hits@10: 0.03
Hits@3: 0.03
Hits@1: 0.02
[146.70868371 185.87978601 176.79842938]


Average ComplEx Loss:   5.126086: 100%|██████████| 10/10 [04:56<00:00, 29.60s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 10.29it/s]


MRR: 0.02
MR: 4430.33
Hits@10: 0.03
Hits@3: 0.03
Hits@1: 0.02
crossover c1: struct({'position': array([146.70868371, 185.87978601, 176.79842938]), 'cost': 0.02451206242073298})
crossover c2: struct({'position': array([146.70868371, 185.87978601, 176.79842938]), 'cost': 0.02451206242073298})
[146.70868371 186.69439239 196.03838633]


Average ComplEx Loss:   5.125418: 100%|██████████| 10/10 [05:33<00:00, 33.30s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 10.88it/s]


MRR: 0.02
MR: 3890.03
Hits@10: 0.03
Hits@3: 0.02
Hits@1: 0.02
[133.95940611 160.26505235 141.36505153]


Average ComplEx Loss:   4.986042: 100%|██████████| 10/10 [03:16<00:00, 19.68s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 14.33it/s]


MRR: 0.00
MR: 4246.03
Hits@10: 0.02
Hits@3: 0.00
Hits@1: 0.00
mutate c3: struct({'position': array([146.70868371, 186.69439239, 196.03838633]), 'cost': 0.021186237985482147})
mutate c4: struct({'position': array([133.95940611, 160.26505235, 141.36505153]), 'cost': 0.0048075543649841864})
P1: struct({'position': array([216.20987624, 150.48667963, 152.00108472]), 'cost': 0.019360949866269173})
P2: struct({'position': array([146.70868371, 185.87978601, 176.79842938]), 'cost': 0.02451206242073298})
[174.71288446 181.79577713 173.70415481]


Average ComplEx Loss:   5.074303: 100%|██████████| 10/10 [04:55<00:00, 29.56s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 10.30it/s]


MRR: 0.03
MR: 4466.73
Hits@10: 0.07
Hits@3: 0.03
Hits@1: 0.00
[188.20567549 154.57068851 155.09535928]


Average ComplEx Loss:   4.884558: 100%|██████████| 10/10 [03:40<00:00, 22.07s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.26it/s]


MRR: 0.03
MR: 4065.38
Hits@10: 0.07
Hits@3: 0.03
Hits@1: 0.02
crossover c1: struct({'position': array([174.71288446, 181.79577713, 173.70415481]), 'cost': 0.025645994383282338})
crossover c2: struct({'position': array([188.20567549, 154.57068851, 155.09535928]), 'cost': 0.03179733301217093})
[159.25065725 165.14154173 173.70415481]


Average ComplEx Loss:   5.033092: 100%|██████████| 10/10 [04:29<00:00, 26.97s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.76it/s]


MRR: 0.05
MR: 4599.23
Hits@10: 0.07
Hits@3: 0.05
Hits@1: 0.03
[188.20567549 166.16102214 148.13914328]


Average ComplEx Loss:   4.960224: 100%|██████████| 10/10 [03:37<00:00, 21.79s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 13.76it/s]


MRR: 0.04
MR: 4880.42
Hits@10: 0.05
Hits@3: 0.05
Hits@1: 0.03
mutate c3: struct({'position': array([159.25065725, 165.14154173, 173.70415481]), 'cost': 0.04671530734115051})
mutate c4: struct({'position': array([188.20567549, 166.16102214, 148.13914328]), 'cost': 0.039656313331342216})
pop: [struct({'position': array([159.25065725, 165.14154173, 173.70415481]), 'cost': 0.04671530734115051}), struct({'position': array([188.20567549, 166.16102214, 148.13914328]), 'cost': 0.039656313331342216}), struct({'position': array([188.20567549, 154.57068851, 155.09535928]), 'cost': 0.03179733301217093})]
Iteration 0: Best Cost = 0.04671530734115051
P1: struct({'position': array([188.20567549, 166.16102214, 148.13914328]), 'cost': 0.039656313331342216})
P2: struct({'position': array([188.20567549, 154.57068851, 155.09535928]), 'cost': 0.03179733301217093})
[188.20567549 164.24412069 152.47802922]


Average ComplEx Loss:   4.947647: 100%|██████████| 10/10 [03:48<00:00, 22.85s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 13.52it/s]


MRR: 0.02
MR: 5008.08
Hits@10: 0.02
Hits@3: 0.02
Hits@1: 0.02
[188.20567549 156.48758996 150.75647335]


Average ComplEx Loss:   4.898886: 100%|██████████| 10/10 [03:38<00:00, 21.89s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.64it/s]


MRR: 0.02
MR: 5025.45
Hits@10: 0.02
Hits@3: 0.02
Hits@1: 0.02
crossover c1: struct({'position': array([188.20567549, 164.24412069, 152.47802922]), 'cost': 0.018956180964215263})
crossover c2: struct({'position': array([188.20567549, 156.48758996, 150.75647335]), 'cost': 0.018937396710281256})
[208.5556183  186.27959003 159.21271503]


Average ComplEx Loss:   5.029951: 100%|██████████| 10/10 [04:31<00:00, 27.15s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.65it/s]


MRR: 0.01
MR: 4820.65
Hits@10: 0.05
Hits@3: 0.00
Hits@1: 0.00
[176.65678992 152.46380068 160.71832983]


Average ComplEx Loss:   4.935933: 100%|██████████| 10/10 [03:35<00:00, 21.54s/epoch]


WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.


100%|██████████| 30/30 [00:02<00:00, 12.62it/s]


MRR: 0.02
MR: 4221.78
Hits@10: 0.02
Hits@3: 0.02
Hits@1: 0.02
mutate c3: struct({'position': array([208.5556183 , 186.27959003, 159.21271503]), 'cost': 0.010745615092033515})
mutate c4: struct({'position': array([176.65678992, 152.46380068, 160.71832983]), 'cost': 0.020765684103685737})
P1: struct({'position': array([188.20567549, 154.57068851, 155.09535928]), 'cost': 0.03179733301217093})
P2: struct({'position': array([188.20567549, 154.57068851, 155.09535928]), 'cost': 0.03179733301217093})
Dynamic Programming
Dynamic Programming
crossover c1: struct({'position': array([188.20567549, 154.57068851, 155.09535928]), 'cost': 0.03179733301217093})
crossover c2: struct({'position': array([188.20567549, 154.57068851, 155.09535928]), 'cost': 0.03179733301217093})
[156.82715037 162.14965727 162.72366152]


Average ComplEx Loss:   4.960729: 100%|██████████| 10/10 [03:56<00:00, 23.69s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 13.11it/s]


MRR: 0.02
MR: 6021.15
Hits@10: 0.03
Hits@3: 0.02
Hits@1: 0.02
[200.15632963 187.51932022 145.31813178]


Average ComplEx Loss:   5.146011: 100%|██████████| 10/10 [04:05<00:00, 24.51s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 14.45it/s]


MRR: 0.03
MR: 5293.28
Hits@10: 0.03
Hits@3: 0.03
Hits@1: 0.02
mutate c3: struct({'position': array([156.82715037, 162.14965727, 162.72366152]), 'cost': 0.02223968487921524})
mutate c4: struct({'position': array([200.15632963, 187.51932022, 145.31813178]), 'cost': 0.02545365768200835})
pop: [struct({'position': array([159.25065725, 165.14154173, 173.70415481]), 'cost': 0.04671530734115051}), struct({'position': array([188.20567549, 166.16102214, 148.13914328]), 'cost': 0.039656313331342216}), struct({'position': array([188.20567549, 154.57068851, 155.09535928]), 'cost': 0.03179733301217093})]
Iteration 1: Best Cost = 0.04671530734115051
P1: struct({'position': array([159.25065725, 165.14154173, 173.70415481]), 'cost': 0.04671530734115051})
P2: struct({'position': array([188.20567549, 166.16102214, 148.13914328]), 'cost': 0.039656313331342216})
[168.18231453 165.61659962 147.89983196]


Average ComplEx Loss:   5.004850: 100%|██████████| 10/10 [03:38<00:00, 21.81s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 14.27it/s]


MRR: 0.00
MR: 4838.63
Hits@10: 0.00
Hits@3: 0.00
Hits@1: 0.00
[179.27401822 165.68596425 173.94346613]


Average ComplEx Loss:   5.012564: 100%|██████████| 10/10 [04:22<00:00, 26.26s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.25it/s]


MRR: 0.05
MR: 4690.25
Hits@10: 0.07
Hits@3: 0.05
Hits@1: 0.03
crossover c1: struct({'position': array([168.18231453, 165.61659962, 147.89983196]), 'cost': 0.0026791057834299288})
crossover c2: struct({'position': array([179.27401822, 165.68596425, 173.94346613]), 'cost': 0.04872378430771676})
[171.1865326  143.7115714  178.70228367]


Average ComplEx Loss:   4.844787: 100%|██████████| 10/10 [04:04<00:00, 24.50s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.18it/s]


MRR: 0.01
MR: 5024.30
Hits@10: 0.05
Hits@3: 0.00
Hits@1: 0.00
[157.8350379  184.02063801 187.32607892]


Average ComplEx Loss:   5.121271: 100%|██████████| 10/10 [05:21<00:00, 32.18s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.18it/s]


MRR: 0.01
MR: 5185.62
Hits@10: 0.02
Hits@3: 0.02
Hits@1: 0.00
mutate c3: struct({'position': array([171.1865326 , 143.7115714 , 178.70228367]), 'cost': 0.007321260540792624})
mutate c4: struct({'position': array([157.8350379 , 184.02063801, 187.32607892]), 'cost': 0.009025734511539743})
P1: struct({'position': array([188.20567549, 154.57068851, 155.09535928]), 'cost': 0.03179733301217093})
P2: struct({'position': array([188.20567549, 154.57068851, 155.09535928]), 'cost': 0.03179733301217093})
[188.20567549 154.57068851 155.09535928]


Average ComplEx Loss:   4.884558: 100%|██████████| 10/10 [03:43<00:00, 22.31s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 13.48it/s]


MRR: 0.03
MR: 4065.38
Hits@10: 0.07
Hits@3: 0.03
Hits@1: 0.02
[188.20567549 154.57068851 155.09535928]


Average ComplEx Loss:   4.884558: 100%|██████████| 10/10 [03:43<00:00, 22.34s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 13.18it/s]


MRR: 0.03
MR: 4065.38
Hits@10: 0.07
Hits@3: 0.03
Hits@1: 0.02
crossover c1: struct({'position': array([188.20567549, 154.57068851, 155.09535928]), 'cost': 0.03179733301217093})
crossover c2: struct({'position': array([188.20567549, 154.57068851, 155.09535928]), 'cost': 0.03179733301217093})
[133.14071416 200.         154.90025354]


Average ComplEx Loss:   5.201179: 100%|██████████| 10/10 [04:24<00:00, 26.41s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 13.05it/s]


MRR: 0.04
MR: 3715.70
Hits@10: 0.08
Hits@3: 0.03
Hits@1: 0.02
[178.14825078 156.8637657  144.09136652]


Average ComplEx Loss:   4.912904: 100%|██████████| 10/10 [03:26<00:00, 20.63s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 13.44it/s]


MRR: 0.00
MR: 4988.35
Hits@10: 0.02
Hits@3: 0.00
Hits@1: 0.00
mutate c3: struct({'position': array([133.14071416, 200.        , 154.90025354]), 'cost': 0.03508685589693946})
mutate c4: struct({'position': array([178.14825078, 156.8637657 , 144.09136652]), 'cost': 0.003766300120920985})
pop: [struct({'position': array([179.27401822, 165.68596425, 173.94346613]), 'cost': 0.04872378430771676}), struct({'position': array([159.25065725, 165.14154173, 173.70415481]), 'cost': 0.04671530734115051}), struct({'position': array([188.20567549, 166.16102214, 148.13914328]), 'cost': 0.039656313331342216})]
Iteration 2: Best Cost = 0.04872378430771676
P1: struct({'position': array([159.25065725, 165.14154173, 173.70415481]), 'cost': 0.04671530734115051})
P2: struct({'position': array([159.25065725, 165.14154173, 173.70415481]), 'cost': 0.04671530734115051})
Dynamic Programming
Dynamic Programming
crossover c1: struct({'position': array([159.25065725, 165.14154173, 173.70415481]), 'cost': 0.0467153073

Average ComplEx Loss:   5.052750: 100%|██████████| 10/10 [03:52<00:00, 23.27s/epoch]


WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.


100%|██████████| 30/30 [00:02<00:00, 12.97it/s]


MRR: 0.03
MR: 4323.32
Hits@10: 0.03
Hits@3: 0.03
Hits@1: 0.02
[136.86689829 165.14154173 190.3556698 ]


Average ComplEx Loss:   5.022062: 100%|██████████| 10/10 [04:46<00:00, 28.62s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.14it/s]


MRR: 0.04
MR: 4253.95
Hits@10: 0.03
Hits@3: 0.03
Hits@1: 0.03
mutate c3: struct({'position': array([143.03737042, 165.14154173, 160.96321189]), 'cost': 0.027228670182712782})
mutate c4: struct({'position': array([136.86689829, 165.14154173, 190.3556698 ]), 'cost': 0.03791500805690262})
P1: struct({'position': array([179.27401822, 165.68596425, 173.94346613]), 'cost': 0.04872378430771676})
P2: struct({'position': array([159.25065725, 165.14154173, 173.70415481]), 'cost': 0.04671530734115051})
[166.34495496 165.44194648 173.71480355]


Average ComplEx Loss:   4.973751: 100%|██████████| 10/10 [04:36<00:00, 27.65s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.44it/s]


MRR: 0.02
MR: 4532.80
Hits@10: 0.07
Hits@3: 0.03
Hits@1: 0.00
[172.1797205  165.38555949 173.93281739]


Average ComplEx Loss:   4.957843: 100%|██████████| 10/10 [04:27<00:00, 26.75s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.78it/s]


MRR: 0.04
MR: 4643.92
Hits@10: 0.07
Hits@3: 0.05
Hits@1: 0.02
crossover c1: struct({'position': array([166.34495496, 165.44194648, 173.71480355]), 'cost': 0.023495583564107986})
crossover c2: struct({'position': array([172.1797205 , 165.38555949, 173.93281739]), 'cost': 0.03672063435905271})
[164.71339147 154.00098141 157.15723978]


Average ComplEx Loss:   4.973777: 100%|██████████| 10/10 [03:38<00:00, 21.82s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.64it/s]


MRR: 0.00
MR: 4863.62
Hits@10: 0.02
Hits@3: 0.00
Hits@1: 0.00
[172.1797205  173.58928163 173.93281739]


Average ComplEx Loss:   5.004087: 100%|██████████| 10/10 [04:47<00:00, 28.77s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.32it/s]


MRR: 0.05
MR: 4551.77
Hits@10: 0.07
Hits@3: 0.07
Hits@1: 0.03
mutate c3: struct({'position': array([164.71339147, 154.00098141, 157.15723978]), 'cost': 0.004013238588769252})
mutate c4: struct({'position': array([172.1797205 , 173.58928163, 173.93281739]), 'cost': 0.04923808253809168})
pop: [struct({'position': array([172.1797205 , 173.58928163, 173.93281739]), 'cost': 0.04923808253809168}), struct({'position': array([179.27401822, 165.68596425, 173.94346613]), 'cost': 0.04872378430771676}), struct({'position': array([159.25065725, 165.14154173, 173.70415481]), 'cost': 0.04671530734115051})]
Iteration 3: Best Cost = 0.04923808253809168
P1: struct({'position': array([159.25065725, 165.14154173, 173.70415481]), 'cost': 0.04671530734115051})
P2: struct({'position': array([179.27401822, 165.68596425, 173.94346613]), 'cost': 0.04872378430771676})
[162.52719421 165.28874282 173.82909174]


Average ComplEx Loss:   5.017073: 100%|██████████| 10/10 [04:23<00:00, 26.39s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.57it/s]


MRR: 0.03
MR: 4768.00
Hits@10: 0.07
Hits@3: 0.02
Hits@1: 0.02
[175.99748126 165.53876316 173.8185292 ]


Average ComplEx Loss:   4.954187: 100%|██████████| 10/10 [04:10<00:00, 25.04s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.80it/s]


MRR: 0.06
MR: 4708.45
Hits@10: 0.07
Hits@3: 0.05
Hits@1: 0.05
crossover c1: struct({'position': array([162.52719421, 165.28874282, 173.82909174]), 'cost': 0.02954513804268814})
crossover c2: struct({'position': array([175.99748126, 165.53876316, 173.8185292 ]), 'cost': 0.056137387860861525})
[174.36487537 152.11860013 177.54639069]


Average ComplEx Loss:   4.900817: 100%|██████████| 10/10 [04:06<00:00, 24.65s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 10.30it/s]


MRR: 0.02
MR: 4103.53
Hits@10: 0.02
Hits@3: 0.02
Hits@1: 0.02
[169.29852465 177.03680061 151.47078637]


Average ComplEx Loss:   5.041732: 100%|██████████| 10/10 [03:55<00:00, 23.54s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 13.77it/s]


MRR: 0.02
MR: 4057.88
Hits@10: 0.02
Hits@3: 0.02
Hits@1: 0.02
mutate c3: struct({'position': array([174.36487537, 152.11860013, 177.54639069]), 'cost': 0.018585887082039333})
mutate c4: struct({'position': array([169.29852465, 177.03680061, 151.47078637]), 'cost': 0.019483463770747108})
P1: struct({'position': array([172.1797205 , 173.58928163, 173.93281739]), 'cost': 0.04923808253809168})
P2: struct({'position': array([159.25065725, 165.14154173, 173.70415481]), 'cost': 0.04671530734115051})
[169.9889483  166.00383785 173.74839778]


Average ComplEx Loss:   4.969925: 100%|██████████| 10/10 [04:26<00:00, 26.64s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.69it/s]


MRR: 0.05
MR: 4447.53
Hits@10: 0.07
Hits@3: 0.07
Hits@1: 0.03
[161.44142945 172.7269855  173.88857442]


Average ComplEx Loss:   5.010140: 100%|██████████| 10/10 [04:13<00:00, 25.40s/epoch]


WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.


100%|██████████| 30/30 [00:02<00:00, 11.94it/s]


MRR: 0.02
MR: 4617.83
Hits@10: 0.05
Hits@3: 0.02
Hits@1: 0.00
crossover c1: struct({'position': array([169.9889483 , 166.00383785, 173.74839778]), 'cost': 0.04993170622659381})
crossover c2: struct({'position': array([161.44142945, 172.7269855 , 173.88857442]), 'cost': 0.016575089478456727})
[191.54127877 152.18230446 173.74839778]


Average ComplEx Loss:   4.873499: 100%|██████████| 10/10 [04:11<00:00, 25.11s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.46it/s]


MRR: 0.05
MR: 4685.20
Hits@10: 0.07
Hits@3: 0.07
Hits@1: 0.03
[160.17054957 200.         171.0448383 ]


Average ComplEx Loss:   5.190471: 100%|██████████| 10/10 [05:04<00:00, 30.41s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.67it/s]


MRR: 0.01
MR: 5447.33
Hits@10: 0.03
Hits@3: 0.00
Hits@1: 0.00
mutate c3: struct({'position': array([191.54127877, 152.18230446, 173.74839778]), 'cost': 0.05222998558127238})
mutate c4: struct({'position': array([160.17054957, 200.        , 171.0448383 ]), 'cost': 0.007551895930348652})
pop: [struct({'position': array([175.99748126, 165.53876316, 173.8185292 ]), 'cost': 0.056137387860861525}), struct({'position': array([191.54127877, 152.18230446, 173.74839778]), 'cost': 0.05222998558127238}), struct({'position': array([169.9889483 , 166.00383785, 173.74839778]), 'cost': 0.04993170622659381})]
Iteration 4: Best Cost = 0.056137387860861525
P1: struct({'position': array([175.99748126, 165.53876316, 173.8185292 ]), 'cost': 0.056137387860861525})
P2: struct({'position': array([169.9889483 , 166.00383785, 173.74839778]), 'cost': 0.04993170622659381})
[173.74602291 165.71258266 173.77141899]


Average ComplEx Loss:   5.012662: 100%|██████████| 10/10 [04:18<00:00, 25.86s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.67it/s]


MRR: 0.06
MR: 4704.12
Hits@10: 0.07
Hits@3: 0.05
Hits@1: 0.05
[172.24040665 165.83001834 173.79550799]


Average ComplEx Loss:   4.957843: 100%|██████████| 10/10 [04:26<00:00, 26.61s/epoch]


WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.


100%|██████████| 30/30 [00:02<00:00, 12.12it/s]


MRR: 0.04
MR: 4643.92
Hits@10: 0.07
Hits@3: 0.05
Hits@1: 0.02
crossover c1: struct({'position': array([173.74602291, 165.71258266, 173.77141899]), 'cost': 0.05620583084943569})
crossover c2: struct({'position': array([172.24040665, 165.83001834, 173.79550799]), 'cost': 0.03672063435905271})
[190.73652129 189.28910395 166.68402057]


Average ComplEx Loss:   5.117875: 100%|██████████| 10/10 [04:37<00:00, 27.77s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.31it/s]


MRR: 0.03
MR: 4353.62
Hits@10: 0.07
Hits@3: 0.03
Hits@1: 0.02
[172.24040665 150.98894879 173.79550799]


Average ComplEx Loss:   4.864740: 100%|██████████| 10/10 [04:04<00:00, 24.49s/epoch]


WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.


100%|██████████| 30/30 [00:02<00:00, 12.43it/s]


MRR: 0.05
MR: 4522.93
Hits@10: 0.08
Hits@3: 0.07
Hits@1: 0.03
mutate c3: struct({'position': array([190.73652129, 189.28910395, 166.68402057]), 'cost': 0.0271547915024866})
mutate c4: struct({'position': array([172.24040665, 150.98894879, 173.79550799]), 'cost': 0.04993925171271407})
P1: struct({'position': array([175.99748126, 165.53876316, 173.8185292 ]), 'cost': 0.056137387860861525})
P2: struct({'position': array([191.54127877, 152.18230446, 173.74839778]), 'cost': 0.05222998558127238})
[177.70601613 153.50107528 173.80091567]


Average ComplEx Loss:   4.908161: 100%|██████████| 10/10 [04:08<00:00, 24.83s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.07it/s]


MRR: 0.03
MR: 4405.63
Hits@10: 0.07
Hits@3: 0.05
Hits@1: 0.00
[189.8327439  164.21999234 173.76601131]


Average ComplEx Loss:   5.001280: 100%|██████████| 10/10 [04:33<00:00, 27.32s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.25it/s]


MRR: 0.05
MR: 4557.18
Hits@10: 0.08
Hits@3: 0.05
Hits@1: 0.03
crossover c1: struct({'position': array([177.70601613, 153.50107528, 173.80091567]), 'cost': 0.02568468844565569})
crossover c2: struct({'position': array([189.8327439 , 164.21999234, 173.76601131]), 'cost': 0.04945758431819986})
[162.84762448 144.45240474 160.38828629]


Average ComplEx Loss:   4.887559: 100%|██████████| 10/10 [03:29<00:00, 20.93s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.97it/s]


MRR: 0.02
MR: 4365.63
Hits@10: 0.02
Hits@3: 0.02
Hits@1: 0.02
[245.92174301 169.64394307 173.76601131]


Average ComplEx Loss:   4.963314: 100%|██████████| 10/10 [04:50<00:00, 29.04s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.22it/s]


MRR: 0.04
MR: 4565.82
Hits@10: 0.08
Hits@3: 0.07
Hits@1: 0.02
mutate c3: struct({'position': array([162.84762448, 144.45240474, 160.38828629]), 'cost': 0.019751967113824917})
mutate c4: struct({'position': array([245.92174301, 169.64394307, 173.76601131]), 'cost': 0.0425780683138299})
pop: [struct({'position': array([173.74602291, 165.71258266, 173.77141899]), 'cost': 0.05620583084943569}), struct({'position': array([175.99748126, 165.53876316, 173.8185292 ]), 'cost': 0.056137387860861525}), struct({'position': array([191.54127877, 152.18230446, 173.74839778]), 'cost': 0.05222998558127238})]
Iteration 5: Best Cost = 0.05620583084943569
P1: struct({'position': array([191.54127877, 152.18230446, 173.74839778]), 'cost': 0.05222998558127238})
P2: struct({'position': array([175.99748126, 165.53876316, 173.8185292 ]), 'cost': 0.056137387860861525})
[188.96004546 161.83247275 173.79910963]


Average ComplEx Loss:   4.918173: 100%|██████████| 10/10 [04:26<00:00, 26.64s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.14it/s]


MRR: 0.05
MR: 4351.05
Hits@10: 0.08
Hits@3: 0.07
Hits@1: 0.03
[178.57871456 155.88859487 173.76781735]


Average ComplEx Loss:   4.892736: 100%|██████████| 10/10 [04:15<00:00, 25.54s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 10.87it/s]


MRR: 0.04
MR: 4587.00
Hits@10: 0.07
Hits@3: 0.07
Hits@1: 0.02
crossover c1: struct({'position': array([188.96004546, 161.83247275, 173.79910963]), 'cost': 0.048420632764954265})
crossover c2: struct({'position': array([178.57871456, 155.88859487, 173.76781735]), 'cost': 0.03847942956007999})
[161.89416838 161.83247275 171.04634717]


Average ComplEx Loss:   4.945460: 100%|██████████| 10/10 [04:00<00:00, 24.10s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.20it/s]


MRR: 0.01
MR: 5570.33
Hits@10: 0.05
Hits@3: 0.02
Hits@1: 0.00
[199.37473942 155.88859487 177.47977637]


Average ComplEx Loss:   4.869975: 100%|██████████| 10/10 [04:22<00:00, 26.23s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 10.16it/s]


MRR: 0.02
MR: 3921.30
Hits@10: 0.02
Hits@3: 0.02
Hits@1: 0.02
mutate c3: struct({'position': array([161.89416838, 161.83247275, 171.04634717]), 'cost': 0.013795184206867863})
mutate c4: struct({'position': array([199.37473942, 155.88859487, 177.47977637]), 'cost': 0.019268156953878842})
P1: struct({'position': array([175.99748126, 165.53876316, 173.8185292 ]), 'cost': 0.056137387860861525})
P2: struct({'position': array([191.54127877, 152.18230446, 173.74839778]), 'cost': 0.05222998558127238})
[185.82458815 153.02050706 173.81910521]


Average ComplEx Loss:   4.860265: 100%|██████████| 10/10 [04:09<00:00, 24.91s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.22it/s]


MRR: 0.03
MR: 4512.23
Hits@10: 0.05
Hits@3: 0.05
Hits@1: 0.02
[181.71417188 164.70056056 173.74782177]


Average ComplEx Loss:   4.949978: 100%|██████████| 10/10 [04:22<00:00, 26.21s/epoch]


WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.


100%|██████████| 30/30 [00:02<00:00, 12.08it/s]


MRR: 0.04
MR: 4579.52
Hits@10: 0.08
Hits@3: 0.05
Hits@1: 0.02
crossover c1: struct({'position': array([185.82458815, 153.02050706, 173.81910521]), 'cost': 0.03350384191272823})
crossover c2: struct({'position': array([181.71417188, 164.70056056, 173.74782177]), 'cost': 0.04237171465924809})
[202.50163151 175.79266907 215.54804664]


Average ComplEx Loss:   4.987600: 100%|██████████| 10/10 [06:15<00:00, 37.52s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:03<00:00,  8.53it/s]


MRR: 0.01
MR: 4015.62
Hits@10: 0.03
Hits@3: 0.00
Hits@1: 0.00
[181.76585342 164.43107621 136.97847039]


Average ComplEx Loss:   4.967901: 100%|██████████| 10/10 [03:15<00:00, 19.58s/epoch]


WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.


100%|██████████| 30/30 [00:01<00:00, 15.35it/s]


MRR: 0.03
MR: 3687.13
Hits@10: 0.08
Hits@3: 0.03
Hits@1: 0.00
mutate c3: struct({'position': array([202.50163151, 175.79266907, 215.54804664]), 'cost': 0.008272355310167573})
mutate c4: struct({'position': array([181.76585342, 164.43107621, 136.97847039]), 'cost': 0.0272363961629723})
pop: [struct({'position': array([173.74602291, 165.71258266, 173.77141899]), 'cost': 0.05620583084943569}), struct({'position': array([175.99748126, 165.53876316, 173.8185292 ]), 'cost': 0.056137387860861525}), struct({'position': array([191.54127877, 152.18230446, 173.74839778]), 'cost': 0.05222998558127238})]
Iteration 6: Best Cost = 0.05620583084943569
P1: struct({'position': array([175.99748126, 165.53876316, 173.8185292 ]), 'cost': 0.056137387860861525})
P2: struct({'position': array([175.99748126, 165.53876316, 173.8185292 ]), 'cost': 0.056137387860861525})
Dynamic Programming
Dynamic Programming
crossover c1: struct({'position': array([175.99748126, 165.53876316, 173.8185292 ]), 'cost': 0.056137387

Average ComplEx Loss:   4.940784: 100%|██████████| 10/10 [03:40<00:00, 22.06s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 13.77it/s]


MRR: 0.03
MR: 4550.43
Hits@10: 0.07
Hits@3: 0.03
Hits@1: 0.02
[200.52935366 165.53876316 172.314061  ]


Average ComplEx Loss:   5.005487: 100%|██████████| 10/10 [04:15<00:00, 25.53s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.11it/s]


MRR: 0.02
MR: 4726.63
Hits@10: 0.03
Hits@3: 0.02
Hits@1: 0.02
mutate c3: struct({'position': array([161.0760066 , 159.3351896 , 153.02291552]), 'cost': 0.03090810161925989})
mutate c4: struct({'position': array([200.52935366, 165.53876316, 172.314061  ]), 'cost': 0.020748147852654823})
P1: struct({'position': array([191.54127877, 152.18230446, 173.74839778]), 'cost': 0.05222998558127238})
P2: struct({'position': array([175.99748126, 165.53876316, 173.8185292 ]), 'cost': 0.056137387860861525})
[180.23002113 154.09703559 173.76715082]


Average ComplEx Loss:   4.916281: 100%|██████████| 10/10 [04:10<00:00, 25.04s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.54it/s]


MRR: 0.06
MR: 4540.28
Hits@10: 0.08
Hits@3: 0.05
Hits@1: 0.05
[187.3087389  163.62403203 173.79977616]


Average ComplEx Loss:   4.957242: 100%|██████████| 10/10 [04:22<00:00, 26.22s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.18it/s]


MRR: 0.02
MR: 4706.10
Hits@10: 0.07
Hits@3: 0.03
Hits@1: 0.00
crossover c1: struct({'position': array([180.23002113, 154.09703559, 173.76715082]), 'cost': 0.05954754028971656})
crossover c2: struct({'position': array([187.3087389 , 163.62403203, 173.79977616]), 'cost': 0.016829828593009334})
[161.6104277  182.12134681 162.81340849]


Average ComplEx Loss:   5.069454: 100%|██████████| 10/10 [04:33<00:00, 27.38s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 13.41it/s]


MRR: 0.02
MR: 6202.23
Hits@10: 0.05
Hits@3: 0.02
Hits@1: 0.02
[180.72055185 154.25720557 172.0181327 ]


Average ComplEx Loss:   4.916255: 100%|██████████| 10/10 [03:58<00:00, 23.87s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.05it/s]


MRR: 0.02
MR: 4735.22
Hits@10: 0.03
Hits@3: 0.02
Hits@1: 0.02
mutate c3: struct({'position': array([161.6104277 , 182.12134681, 162.81340849]), 'cost': 0.023911740206173607})
mutate c4: struct({'position': array([180.72055185, 154.25720557, 172.0181327 ]), 'cost': 0.022506343739149535})
pop: [struct({'position': array([180.23002113, 154.09703559, 173.76715082]), 'cost': 0.05954754028971656}), struct({'position': array([173.74602291, 165.71258266, 173.77141899]), 'cost': 0.05620583084943569}), struct({'position': array([175.99748126, 165.53876316, 173.8185292 ]), 'cost': 0.056137387860861525})]
Iteration 7: Best Cost = 0.05954754028971656
P1: struct({'position': array([173.74602291, 165.71258266, 173.77141899]), 'cost': 0.05620583084943569})
P2: struct({'position': array([173.74602291, 165.71258266, 173.77141899]), 'cost': 0.05620583084943569})
Dynamic Programming
Dynamic Programming
crossover c1: struct({'position': array([173.74602291, 165.71258266, 173.77141899]), 'cost': 0.056205830

Average ComplEx Loss:   4.836141: 100%|██████████| 10/10 [05:03<00:00, 30.35s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 10.55it/s]


MRR: 0.03
MR: 5360.05
Hits@10: 0.03
Hits@3: 0.03
Hits@1: 0.02
[181.39203133 165.71258266 172.23175043]


Average ComplEx Loss:   4.955972: 100%|██████████| 10/10 [04:25<00:00, 26.54s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.13it/s]


MRR: 0.02
MR: 4737.45
Hits@10: 0.02
Hits@3: 0.02
Hits@1: 0.02
mutate c3: struct({'position': array([190.79456683, 145.32865029, 205.1137344 ]), 'cost': 0.02753580636700741})
mutate c4: struct({'position': array([181.39203133, 165.71258266, 172.23175043]), 'cost': 0.020162521273648044})
P1: struct({'position': array([173.74602291, 165.71258266, 173.77141899]), 'cost': 0.05620583084943569})
P2: struct({'position': array([180.23002113, 154.09703559, 173.76715082]), 'cost': 0.05954754028971656})
[175.32618033 155.6849684  173.76825548]


Average ComplEx Loss:   4.893292: 100%|██████████| 10/10 [04:03<00:00, 24.34s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.76it/s]


MRR: 0.05
MR: 4301.90
Hits@10: 0.08
Hits@3: 0.05
Hits@1: 0.03
[178.64986371 164.12464985 173.77031433]


Average ComplEx Loss:   4.947732: 100%|██████████| 10/10 [04:19<00:00, 25.90s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.58it/s]


MRR: 0.06
MR: 4487.98
Hits@10: 0.07
Hits@3: 0.07
Hits@1: 0.05
crossover c1: struct({'position': array([175.32618033, 155.6849684 , 173.76825548]), 'cost': 0.048399022206956174})
crossover c2: struct({'position': array([178.64986371, 164.12464985, 173.77031433]), 'cost': 0.06136344437072937})
[199.13369647 148.43457012 172.71215986]


Average ComplEx Loss:   4.827632: 100%|██████████| 10/10 [04:03<00:00, 24.32s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.31it/s]


MRR: 0.02
MR: 4556.78
Hits@10: 0.05
Hits@3: 0.02
Hits@1: 0.02
[180.62405832 149.419723   171.16080776]


Average ComplEx Loss:   4.883859: 100%|██████████| 10/10 [03:53<00:00, 23.36s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.41it/s]


MRR: 0.02
MR: 5378.72
Hits@10: 0.05
Hits@3: 0.02
Hits@1: 0.02
mutate c3: struct({'position': array([199.13369647, 148.43457012, 172.71215986]), 'cost': 0.0230757138295301})
mutate c4: struct({'position': array([180.62405832, 149.419723  , 171.16080776]), 'cost': 0.022454787551823077})
pop: [struct({'position': array([178.64986371, 164.12464985, 173.77031433]), 'cost': 0.06136344437072937}), struct({'position': array([180.23002113, 154.09703559, 173.76715082]), 'cost': 0.05954754028971656}), struct({'position': array([173.74602291, 165.71258266, 173.77141899]), 'cost': 0.05620583084943569})]
Iteration 8: Best Cost = 0.06136344437072937
P1: struct({'position': array([178.64986371, 164.12464985, 173.77031433]), 'cost': 0.06136344437072937})
P2: struct({'position': array([173.74602291, 165.71258266, 173.77141899]), 'cost': 0.05620583084943569})
[175.23640146 164.33681174 173.77122489]


Average ComplEx Loss:   4.948378: 100%|██████████| 10/10 [04:17<00:00, 25.73s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.03it/s]


MRR: 0.03
MR: 4358.20
Hits@10: 0.08
Hits@3: 0.05
Hits@1: 0.00
[177.15948517 165.50042078 173.77050844]


Average ComplEx Loss:   4.982384: 100%|██████████| 10/10 [04:20<00:00, 26.01s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.91it/s]


MRR: 0.04
MR: 4705.67
Hits@10: 0.07
Hits@3: 0.05
Hits@1: 0.02
crossover c1: struct({'position': array([175.23640146, 164.33681174, 173.77122489]), 'cost': 0.028012353385414784})
crossover c2: struct({'position': array([177.15948517, 165.50042078, 173.77050844]), 'cost': 0.03683712806236697})
[158.8462208  129.38742429 195.48681362]


Average ComplEx Loss:   4.737536: 100%|██████████| 10/10 [04:11<00:00, 25.14s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.26it/s]


MRR: 0.01
MR: 4030.98
Hits@10: 0.03
Hits@3: 0.02
Hits@1: 0.00
[193.90538493 164.60692506 178.89853695]


Average ComplEx Loss:   4.985133: 100%|██████████| 10/10 [04:31<00:00, 27.10s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.97it/s]


MRR: 0.00
MR: 5172.72
Hits@10: 0.00
Hits@3: 0.00
Hits@1: 0.00
mutate c3: struct({'position': array([158.8462208 , 129.38742429, 195.48681362]), 'cost': 0.013484088632374389})
mutate c4: struct({'position': array([193.90538493, 164.60692506, 178.89853695]), 'cost': 0.0031679077040606537})
P1: struct({'position': array([178.64986371, 164.12464985, 173.77031433]), 'cost': 0.06136344437072937})
P2: struct({'position': array([180.23002113, 154.09703559, 173.76715082]), 'cost': 0.05954754028971656})
[179.79143464 156.05339531 173.77020202]


Average ComplEx Loss:   4.957117: 100%|██████████| 10/10 [04:16<00:00, 25.69s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.40it/s]


MRR: 0.03
MR: 4589.95
Hits@10: 0.05
Hits@3: 0.05
Hits@1: 0.02
[179.0884502  162.16829013 173.76726313]


Average ComplEx Loss:   4.994393: 100%|██████████| 10/10 [04:18<00:00, 25.88s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 12.44it/s]


MRR: 0.02
MR: 4577.93
Hits@10: 0.07
Hits@3: 0.03
Hits@1: 0.00
crossover c1: struct({'position': array([179.79143464, 156.05339531, 173.77020202]), 'cost': 0.03248166986225792})
crossover c2: struct({'position': array([179.0884502 , 162.16829013, 173.76726313]), 'cost': 0.022349092870283634})
[166.05866645 169.21638111 181.5864409 ]


Average ComplEx Loss:   4.993770: 100%|██████████| 10/10 [04:52<00:00, 29.25s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 11.59it/s]


MRR: 0.03
MR: 4322.20
Hits@10: 0.10
Hits@3: 0.05
Hits@1: 0.00
[179.86642204 153.5023758  162.93076227]


Average ComplEx Loss:   4.943073: 100%|██████████| 10/10 [03:45<00:00, 22.57s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 30/30 [00:02<00:00, 13.39it/s]


MRR: 0.02
MR: 6158.02
Hits@10: 0.03
Hits@3: 0.03
Hits@1: 0.02
mutate c3: struct({'position': array([166.05866645, 169.21638111, 181.5864409 ]), 'cost': 0.025773611594494227})
mutate c4: struct({'position': array([179.86642204, 153.5023758 , 162.93076227]), 'cost': 0.023796547114202385})
pop: [struct({'position': array([178.64986371, 164.12464985, 173.77031433]), 'cost': 0.06136344437072937}), struct({'position': array([180.23002113, 154.09703559, 173.76715082]), 'cost': 0.05954754028971656}), struct({'position': array([173.74602291, 165.71258266, 173.77141899]), 'cost': 0.05620583084943569})]
Iteration 9: Best Cost = 0.06136344437072937
[struct({'position': array([178.64986371, 164.12464985, 173.77031433]), 'cost': 0.06136344437072937}), struct({'position': array([180.23002113, 154.09703559, 173.76715082]), 'cost': 0.05954754028971656}), struct({'position': array([173.74602291, 165.71258266, 173.77141899]), 'cost': 0.05620583084943569})]
struct({'position': array([178.64986371, 164.124

In [ ]:
df = pd.DataFrame({"position": [bestSolution[0].position] , "cost": [bestSolution[0].cost]})
for i in range(params.maxit):
    if(i==0):
        continue;
    df.loc[len(df.index)] = [bestSolution[i].position , bestSolution[i].cost] 
df.to_excel('result.xlsx')
df

position      cost
0  [159.250657249938, 165.14154172661915, 173.704...  0.046715
1  [159.250657249938, 165.14154172661915, 173.704...  0.046715
2  [179.27401821522236, 165.68596424944988, 173.9...  0.048724
3  [172.17972050285422, 173.58928162665177, 173.9...  0.049238
4  [175.99748125993602, 165.53876315782668, 173.8...  0.056137
5  [173.74602291433166, 165.7125826648479, 173.77...  0.056206
6  [173.74602291433166, 165.7125826648479, 173.77...  0.056206
7  [180.23002112894343, 154.09703558929561, 173.7...  0.059548
8  [178.64986371195863, 164.12464985243906, 173.7...  0.061363
9  [178.64986371195863, 164.12464985243906, 173.7...  0.061363

In [ ]:
popc = []
npop = 3
varmin = 30
varmax = 300
nvar = 3


# Empty Individual Template
empty_individual = structure()
empty_individual.position = None
empty_individual.cost = None

# Best Solution Ever Found
bestsol = empty_individual.deepcopy()
bestsol.cost = 0

pop = empty_individual.repeat(npop)

# Initialize Population
for i in range(npop):
    pop[i].position = np.random.uniform(varmin, varmax, nvar) 
    pop[i].cost = i
    print(pop[i])

flag = False
for element in pop:
  print(element.cost)
  if (np.array_equal(pop[1].position , pop[2].position)):
    pop[1].cost = element[2].cost
    flag = True
    break;
if (flag == False):
  print(flag)


struct({'position': array([154.12295069,  57.65641769, 277.67867892]), 'cost': 0})
struct({'position': array([ 39.17237414,  41.5234883 , 245.87143436]), 'cost': 1})
struct({'position': array([168.14678061, 163.63311539, 205.46627005]), 'cost': 2})
0
1
2
False
