<a href="https://colab.research.google.com/github/mohammadRahimi1993/BigData/blob/main/CheckGAFineTune.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%%capture 
!pip install ampligraph; 

In [ ]:
%tensorflow_version 1.x
!pip install tensorflow==1.15.2;  
!pip install ypstruct;

TensorFlow 1.x selected.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7554 sha256=9738bcf794be373af3535d357e3eba9f5ac301bb902acc98645025f5b7a48790
  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
Successfully built gast
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 4.2.0
    Uninstalling importlib-metadata-4.2.0:
      Successfully uninstalled importlib-metadata-4.2.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Successfully uninstalled gast-0.5.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
kapre 0.3.7 requires tensorflow>=2.0.0, but you have tensorflow 1.15.2 which is i

In [ ]:
import numpy as np;
import pandas as pd;
import ampligraph;
import numpy as np
import matplotlib.pyplot as plt
from ypstruct import structure
import numpy as np;
import pandas as pd;
import ampligraph;

In [ ]:
def dataPreparing():
#def costFunction():
    from ampligraph.evaluation import train_test_split_no_unseen  
    import requests
    url = 'https://ampligraph.s3-eu-west-1.amazonaws.com/datasets/football_graph.csv'
    open('football_results.csv', 'wb').write(requests.get(url).content)
    df = pd.read_csv("football_results.csv").sort_values("date")
    print(df.isna().sum())
    df = df.dropna()
    df["train"] = df.date < "2014-01-01"
    print(df.train.value_counts())
        # Entities naming
    df["match_id"] = df.index.values.astype(str)
    df["match_id"] =  "Match" + df.match_id
    df["city_id"] = "City" + df.city.str.title().str.replace(" ", "")
    df["country_id"] = "Country" + df.country.str.title().str.replace(" ", "")
    df["home_team_id"] = "Team" + df.home_team.str.title().str.replace(" ", "")
    df["away_team_id"] = "Team" + df.away_team.str.title().str.replace(" ", "")
    df["tournament_id"] = "Tournament" + df.tournament.str.title().str.replace(" ", "")
    df["neutral"] = df.neutral.astype(str)
    
    triples = []
    for _, row in df[df["train"]].iterrows():
        # Home and away information
        home_team = (row["home_team_id"], "isHomeTeamIn", row["match_id"])
        away_team = (row["away_team_id"], "isAwayTeamIn", row["match_id"])
    
        # Match results
        if row["home_score"] > row["away_score"]:
            score_home = (row["home_team_id"], "winnerOf", row["match_id"])
            score_away = (row["away_team_id"], "loserOf", row["match_id"])
        elif row["home_score"] < row["away_score"]:
            score_away = (row["away_team_id"], "winnerOf", row["match_id"])
            score_home = (row["home_team_id"], "loserOf", row["match_id"])
        else:
            score_home = (row["home_team_id"], "draws", row["match_id"])
            score_away = (row["away_team_id"], "draws", row["match_id"])
        home_score = (row["match_id"], "homeScores", np.clip(int(row["home_score"]), 0, 5))
        away_score = (row["match_id"], "awayScores", np.clip(int(row["away_score"]), 0, 5))
    
        # Match characteristics
        tournament = (row["match_id"], "inTournament", row["tournament_id"])
        city = (row["match_id"], "inCity", row["city_id"])
        country = (row["match_id"], "inCountry", row["country_id"])
        neutral = (row["match_id"], "isNeutral", row["neutral"])
        year = (row["match_id"], "atYear", row["date"][:4])
    
        triples.extend((home_team, away_team, score_home, score_away, 
                        tournament, city, country, neutral, year, home_score, away_score))
    triples_df = pd.DataFrame(triples, columns=["subject", "predicate", "object"])
    triples_df[(triples_df.subject=="Match3129") | (triples_df.object=="Match3129")]
    
    X_train, X_valid = train_test_split_no_unseen(np.array(triples), test_size=10000)
    print('Train set size: ', X_train.shape)
    print('Test set size: ', X_valid.shape)
    return X_train, X_valid

In [ ]:
X_train, X_valid=dataPreparing()

date          0
home_team     0
away_team     0
home_score    2
away_score    2
tournament    0
city          0
country       0
neutral       0
dtype: int64
True     35714
False     5057
Name: train, dtype: int64
Train set size:  (382854, 3)
Test set size:  (10000, 3)


In [ ]:
def costFunction(X, X_train, X_valid):
    from ampligraph.latent_features import ComplEx
    model = ComplEx(batches_count=int(X[0]),
                    epochs=10,
                    k=int(X[2]),
                    eta=int(X[1]),
                    optimizer='adam', 
                    optimizer_params={'lr':1e-4},
                    loss='multiclass_nll',
                    regularizer='LP', 
                    regularizer_params={'p':3, 'lambda':1e-5}, 
                    seed=0, 
                    verbose=True)
    import tensorflow as tf
    tf.logging.set_verbosity(tf.logging.ERROR)
    model.fit(X_train)
    #model.fit(X_train[:10000,:10000])
    filter_triples = np.concatenate((X_train, X_valid))
    from ampligraph.evaluation import evaluate_performance
    #ranks = evaluate_performance(X_valid[:100,:200],
    #                             model=model, 
    #                             filter_triples=filter_triples,
    #                             use_default_protocol=True,
    #                             verbose=True)
    ranks = evaluate_performance(X_valid,
                                 model=model, 
                                 filter_triples=filter_triples,
                                 use_default_protocol=True,
                                 verbose=True)
    
    from ampligraph.evaluation import mr_score, mrr_score, hits_at_n_score

    mr = mr_score(ranks)
    mrr = mrr_score(ranks)

    print("MRR: %.2f" % (mrr))
    print("MR: %.2f" % (mr))

    hits_10 = hits_at_n_score(ranks, n=10)
    print("Hits@10: %.2f" % (hits_10))
    hits_3 = hits_at_n_score(ranks, n=3)
    print("Hits@3: %.2f" % (hits_3))
    hits_1 = hits_at_n_score(ranks, n=1)
    print("Hits@1: %.2f" % (hits_1))
    return float(mrr)


In [ ]:
def crossover(p1, p2, gamma=0.1):
    c1 = p1.deepcopy()
    c2 = p1.deepcopy()
    alpha = np.random.uniform(-gamma, 1+gamma, *c1.position.shape)
    print('alpha:', alpha)
    c1.position = alpha*p1.position + (1-alpha)*p2.position
    print('alpha*p1.position:', alpha*p1.position)
    print('(1-alpha)*p2.position',(1-alpha)*p2.position)
    c2.position = alpha*p2.position + (1-alpha)*p1.position
    print('alpha*p1.position:', alpha*p2.position)
    print('(1-alpha)*p2.position',(1-alpha)*p1.position)
    return c1, c2

def mutate(x, mu, sigma):
    y = x.deepcopy()
    flag = np.random.rand(*x.position.shape) <= mu
    ind = np.argwhere(flag)
    y.position[ind] += sigma*np.random.randn(*ind.shape)
    return y

def apply_bound(x, varmin, varmax):
    x.position = np.maximum(x.position, varmin)
    x.position = np.minimum(x.position, varmax)

def roulette_wheel_selection(p):
    c = np.cumsum(p)
    r = sum(p)*np.random.rand()
    ind = np.argwhere(r <= c)
    return ind[0][0]


In [ ]:
# Problem Definition
problem = structure()
problem.costFunc = costFunction
problem.nvar = 3
#X[0]:Batch ,X[1]:eta ,X[2]:Dimention Of Embbeding
problem.varmin = [30,20,30]
problem.varmax = [100,70,100]

# GA Parameters
params = structure()
params.maxit = 15
params.npop = 3
params.beta = 1
params.pc = 1
params.gamma = 0.1
params.mu = 0.9
params.sigma = 20

In [ ]:
# Problem Information
# costFunction = problem.costFunction
popc = []
nvar = problem.nvar
varmin = problem.varmin
varmax = problem.varmax

# Parameters
maxit = params.maxit
npop = params.npop
beta = params.beta
pc = params.pc
nc = int(np.round(pc*npop/2)*2)
gamma = params.gamma
mu = params.mu
sigma = params.sigma

# Empty Individual Template
empty_individual = structure()
empty_individual.position = None
empty_individual.cost = None

# Best Solution Ever Found
bestsol = empty_individual.deepcopy()
bestsol.cost = 0

pop = empty_individual.repeat(npop)
bestSolution = empty_individual.repeat(maxit)

# Initialize Population
for i in range(npop):
    pop[i].position = np.random.uniform(varmin, varmax, nvar) 
    print(pop[i].position)
for i in range(npop):
    print(pop[i].position)
    pop[i].cost = costFunction(pop[i].position, X_train, X_valid)
    print(pop[i].cost)
    if pop[i].cost > bestsol.cost:
        bestsol = pop[i].deepcopy()
    popc.append(pop[i])

# Best Cost of Iterations
bestposition = np.empty(maxit)
bestcost = np.empty(maxit)

# Main Loop
for it in range(maxit):
    costs = np.array([x.cost for x in pop])
    avg_cost = np.mean(costs)
    if avg_cost != 0:
        costs = costs/avg_cost
    probs = np.exp(-beta*costs)

    for _ in range(nc//2):

        # Select Parents
        #q = np.random.permutation(npop)
        #p1 = pop[q[0]]
        #p2 = pop[q[1]]

        # Perform Roulette Wheel Selection
        p1 = pop[roulette_wheel_selection(probs)]
        p2 = pop[roulette_wheel_selection(probs)]
        print('P1:', p1)
        print('P2:',p2)
  
        # Perform Crossover
        # c1, c2 = crossover(p1, p2, gamma)
        gamma = 0.01
        c1 = p1.deepcopy()
        c2 = p2.deepcopy()
        alpha = np.random.uniform(-gamma, 1+gamma, *c1.position.shape)
        c1.position = alpha*p1.position + (1-alpha)*p2.position
        c2.position = alpha*p2.position + (1-alpha)*p1.position
        apply_bound(c1, varmin, varmax)
        apply_bound(c2, varmin, varmax)

        # Evaluate First Offspring
        flag = False
        for element in popc:
          if (np.array_equal(element.position , c1.position)):
            print("Dynamic Programming")
            c1.cost = element.cost
            flag = True
            break;
        if (flag == False):
          print(c1.position) 
          c1.cost = costFunction(c1.position, X_train, X_valid)
          if c1.cost > bestsol.cost:
            bestsol = c1.deepcopy()

        # Evaluate Second Offspring
        flag = False
        for element in popc:
          if (np.array_equal(element.position , c2.position)):
            print("Dynamic Programming")
            c2.cost = element.cost
            flag = True
            break;
        if (flag == False):
          print(c2.position) 
          c2.cost = costFunction(c2.position, X_train, X_valid)
          if c2.cost > bestsol.cost:
            bestsol = c2.deepcopy()

        print('crossover c1:',c1)
        print('crossover c2:',c2) 

        # Perform Mutation
        c3 = c1.deepcopy()
        flag = np.random.rand(*c1.position.shape) <= mu
        ind = np.argwhere(flag)
        c3.position[ind] += sigma*np.random.randn(*ind.shape)
        #c1 = mutate(c1, mu, sigma)
        c4 = c2.deepcopy()
        flag = np.random.rand(*c2.position.shape) <= mu
        ind = np.argwhere(flag)
        c4.position[ind] += sigma*np.random.randn(*ind.shape)
        #c2 = mutate(c2, mu, sigma)
              
        # Apply Bounds
        apply_bound(c3, varmin, varmax)
        apply_bound(c4, varmin, varmax)

        # Evaluate Thirty Offspring
        flag = False
        for element in popc:
          if (np.array_equal(element.position , c3.position)):
            print("Dynamic Programming")
            c3.cost = element.cost
            flag = True
            break;
        if (flag == False):
          print(c3.position) 
          c3.cost = costFunction(c3.position, X_train, X_valid)
          if c3.cost > bestsol.cost:
            bestsol = c3.deepcopy()

        # Evaluate Fortith Offspring
        flag = False
        for element in popc:
          if (np.array_equal(element.position , c4.position)):
            print("Dynamic Programming")
            c4.cost = element.cost
            flag = True
            break;
        if (flag == False):
          print(c4.position) 
          c4.cost = costFunction(c4.position, X_train, X_valid)
          if c4.cost > bestsol.cost:
            bestsol = c4.deepcopy()

        print('mutate c3:',c3)
        print('mutate c4:',c4) 
        # Add Offsprings to popc

        popc.append(c1)
        popc.append(c2)
        popc.append(c3)
        popc.append(c4)
        
        # Check pop list for insert c1,c2,c3,c4
        flag = False
        for element in pop:
          flag = np.array_equal(element.position, c1.position)
          if flag == True:
            break
        if flag == False:
          pop.append(c1)
        
        flag = False
        for element in pop:
          flag = np.array_equal(element.position, c2.position)
          if flag == True:
            break
        if flag == False:
          pop.append(c2)

        flag = False
        for element in pop:
          flag = np.array_equal(element.position, c3.position)
          if flag == True:
            break
        if flag == False:
          pop.append(c3)

        flag = False
        for element in pop:
          flag = np.array_equal(element.position, c4.position)
          if flag == True:
            break
        if flag == False:
          pop.append(c4)


    # Merge, Sort and Select
    # pop += popc
    pop = sorted(pop, key=lambda x: x.cost, reverse=True)
    pop = pop[0:npop]
    print('pop:' , pop)
    
    # Store Best Cost
    bestcost[it] = bestsol.cost

    bestSolution[it].cost = bestsol.cost
    bestSolution[it].position = bestsol.position
                               
    # Show Iteration Information
    print("Iteration {}: Best Cost = {}".format(it, bestcost[it]))


# Output
out = structure()
out.pop = pop
out.bestsol = bestsol
out.bestcost = bestcost
print(out.pop)
print(out.bestsol)
print(out.bestcost)

[46.3480393  66.07771834 57.77267583]
[70.67345668 56.2462999  53.0812863 ]
[51.47704488 53.30424993 73.61647217]
[46.3480393  66.07771834 57.77267583]


Average ComplEx Loss:   4.199490: 100%|██████████| 10/10 [00:52<00:00,  5.21s/epoch]


WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.


100%|██████████| 10000/10000 [02:44<00:00, 60.62it/s]


MRR: 0.10
MR: 10490.63
Hits@10: 0.17
Hits@3: 0.12
Hits@1: 0.07
0.10480533983728282
[70.67345668 56.2462999  53.0812863 ]


Average ComplEx Loss:   4.028870: 100%|██████████| 10/10 [00:41<00:00,  4.19s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:40<00:00, 62.32it/s]


MRR: 0.13
MR: 9408.13
Hits@10: 0.21
Hits@3: 0.15
Hits@1: 0.09
0.12931213532990843
[51.47704488 53.30424993 73.61647217]


Average ComplEx Loss:   3.980380: 100%|██████████| 10/10 [00:52<00:00,  5.21s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:50<00:00, 58.49it/s]


MRR: 0.14
MR: 8934.97
Hits@10: 0.23
Hits@3: 0.16
Hits@1: 0.09
0.13884218434809417
P1: struct({'position': array([46.3480393 , 66.07771834, 57.77267583]), 'cost': 0.10480533983728282})
P2: struct({'position': array([46.3480393 , 66.07771834, 57.77267583]), 'cost': 0.10480533983728282})
[46.3480393  66.07771834 57.77267583]


Average ComplEx Loss:   4.199490: 100%|██████████| 10/10 [00:51<00:00,  5.17s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:41<00:00, 61.91it/s]


MRR: 0.10
MR: 10490.63
Hits@10: 0.17
Hits@3: 0.12
Hits@1: 0.07
[46.3480393  66.07771834 57.77267583]


Average ComplEx Loss:   4.199490: 100%|██████████| 10/10 [00:51<00:00,  5.18s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:42<00:00, 61.67it/s]


MRR: 0.10
MR: 10490.63
Hits@10: 0.17
Hits@3: 0.12
Hits@1: 0.07
crossover c1: struct({'position': array([46.3480393 , 66.07771834, 57.77267583]), 'cost': 0.1048053420401061})
crossover c2: struct({'position': array([46.3480393 , 66.07771834, 57.77267583]), 'cost': 0.10480533982992472})
[46.3480393  66.89232472 77.01263278]


Average ComplEx Loss:   4.197431: 100%|██████████| 10/10 [01:06<00:00,  6.69s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:51<00:00, 58.29it/s]


MRR: 0.14
MR: 9445.26
Hits@10: 0.22
Hits@3: 0.16
Hits@1: 0.10
[33.5987617  40.46298467 30.        ]


Average ComplEx Loss:   3.711869: 100%|██████████| 10/10 [00:18<00:00,  1.87s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:29<00:00, 66.97it/s]


MRR: 0.07
MR: 11213.39
Hits@10: 0.12
Hits@3: 0.08
Hits@1: 0.04
mutate c3: struct({'position': array([46.3480393 , 66.89232472, 77.01263278]), 'cost': 0.13925362482588702})
mutate c4: struct({'position': array([33.5987617 , 40.46298467, 30.        ]), 'cost': 0.06910762776683371})
P1: struct({'position': array([70.67345668, 56.2462999 , 53.0812863 ]), 'cost': 0.12931213532990843})
P2: struct({'position': array([46.3480393 , 66.07771834, 57.77267583]), 'cost': 0.10480533983728282})
[56.14950956 64.94327143 57.18727253]


Average ComplEx Loss:   4.165973: 100%|██████████| 10/10 [00:50<00:00,  5.04s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:45<00:00, 60.53it/s]


MRR: 0.11
MR: 10176.77
Hits@10: 0.19
Hits@3: 0.13
Hits@1: 0.08
[60.87198642 57.38074681 53.66668959]


Average ComplEx Loss:   4.050877: 100%|██████████| 10/10 [00:42<00:00,  4.23s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:42<00:00, 61.55it/s]


MRR: 0.12
MR: 9546.59
Hits@10: 0.20
Hits@3: 0.14
Hits@1: 0.08
crossover c1: struct({'position': array([56.14950956, 64.94327143, 57.18727253]), 'cost': 0.11376104134131619})
crossover c2: struct({'position': array([60.87198642, 57.38074681, 53.66668959]), 'cost': 0.12398613476608839})
[40.68728235 48.28903602 57.18727253]


Average ComplEx Loss:   3.887878: 100%|██████████| 10/10 [00:38<00:00,  3.81s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:43<00:00, 61.25it/s]


MRR: 0.10
MR: 10760.78
Hits@10: 0.16
Hits@3: 0.11
Hits@1: 0.07
[60.87198642 68.97108044 46.7104736 ]


Average ComplEx Loss:   4.225782: 100%|██████████| 10/10 [00:43<00:00,  4.39s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:41<00:00, 62.09it/s]


MRR: 0.12
MR: 9117.49
Hits@10: 0.20
Hits@3: 0.14
Hits@1: 0.08
mutate c3: struct({'position': array([40.68728235, 48.28903602, 57.18727253]), 'cost': 0.09805394191152138})
mutate c4: struct({'position': array([60.87198642, 68.97108044, 46.7104736 ]), 'cost': 0.1206197456455078})
pop: [struct({'position': array([46.3480393 , 66.89232472, 77.01263278]), 'cost': 0.13925362482588702}), struct({'position': array([51.47704488, 53.30424993, 73.61647217]), 'cost': 0.13884218434809417}), struct({'position': array([70.67345668, 56.2462999 , 53.0812863 ]), 'cost': 0.12931213532990843})]
Iteration 0: Best Cost = 0.13925362482588702
P1: struct({'position': array([51.47704488, 53.30424993, 73.61647217]), 'cost': 0.13884218434809417})
P2: struct({'position': array([51.47704488, 53.30424993, 73.61647217]), 'cost': 0.13884218434809417})
[51.47704488 53.30424993 73.61647217]


Average ComplEx Loss:   3.980380: 100%|██████████| 10/10 [00:51<00:00,  5.17s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:51<00:00, 58.41it/s]


MRR: 0.14
MR: 8934.97
Hits@10: 0.23
Hits@3: 0.16
Hits@1: 0.09
[51.47704488 53.30424993 73.61647217]


Average ComplEx Loss:   3.980380: 100%|██████████| 10/10 [00:51<00:00,  5.16s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:49<00:00, 58.83it/s]


MRR: 0.14
MR: 8934.97
Hits@10: 0.23
Hits@3: 0.16
Hits@1: 0.09
crossover c1: struct({'position': array([51.47704488, 53.30424993, 73.61647217]), 'cost': 0.1388421446641633})
crossover c2: struct({'position': array([51.47704488, 53.30424993, 73.61647217]), 'cost': 0.13884214466375905})
[71.82698769 70.         80.35115798]


Average ComplEx Loss:   4.240055: 100%|██████████| 10/10 [01:06<00:00,  6.68s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:50<00:00, 58.61it/s]


MRR: 0.16
MR: 9290.63
Hits@10: 0.25
Hits@3: 0.18
Hits@1: 0.11
[39.92815932 49.28046065 83.57832865]


Average ComplEx Loss:   3.906871: 100%|██████████| 10/10 [00:53<00:00,  5.37s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:58<00:00, 55.93it/s]


MRR: 0.14
MR: 8773.49
Hits@10: 0.22
Hits@3: 0.15
Hits@1: 0.09
mutate c3: struct({'position': array([71.82698769, 70.        , 80.35115798]), 'cost': 0.15680229017783076})
mutate c4: struct({'position': array([39.92815932, 49.28046065, 83.57832865]), 'cost': 0.13695187494039715})
P1: struct({'position': array([70.67345668, 56.2462999 , 53.0812863 ]), 'cost': 0.12931213532990843})
P2: struct({'position': array([70.67345668, 56.2462999 , 53.0812863 ]), 'cost': 0.12931213532990843})
Dynamic Programming
Dynamic Programming
crossover c1: struct({'position': array([70.67345668, 56.2462999 , 53.0812863 ]), 'cost': 0.12931213532990843})
crossover c2: struct({'position': array([70.67345668, 56.2462999 , 53.0812863 ]), 'cost': 0.12931213532990843})
[39.29493156 63.82526866 60.70958854]


Average ComplEx Loss:   4.154846: 100%|██████████| 10/10 [00:50<00:00,  5.05s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:45<00:00, 60.32it/s]


MRR: 0.11
MR: 10885.03
Hits@10: 0.18
Hits@3: 0.12
Hits@1: 0.07
[82.62411083 70.         43.30405879]


Average ComplEx Loss:   4.244762: 100%|██████████| 10/10 [00:43<00:00,  4.34s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:37<00:00, 63.69it/s]


MRR: 0.12
MR: 9948.08
Hits@10: 0.20
Hits@3: 0.14
Hits@1: 0.08
mutate c3: struct({'position': array([39.29493156, 63.82526866, 60.70958854]), 'cost': 0.10674929775630301})
mutate c4: struct({'position': array([82.62411083, 70.        , 43.30405879]), 'cost': 0.12157022432902125})
pop: [struct({'position': array([71.82698769, 70.        , 80.35115798]), 'cost': 0.15680229017783076}), struct({'position': array([46.3480393 , 66.89232472, 77.01263278]), 'cost': 0.13925362482588702}), struct({'position': array([51.47704488, 53.30424993, 73.61647217]), 'cost': 0.13884218434809417})]
Iteration 1: Best Cost = 0.15680229017783076
P1: struct({'position': array([71.82698769, 70.        , 80.35115798]), 'cost': 0.15680229017783076})
P2: struct({'position': array([46.3480393 , 66.89232472, 77.01263278]), 'cost': 0.13925362482588702})
[63.96758201 68.55188423 76.98138121]


Average ComplEx Loss:   4.218596: 100%|██████████| 10/10 [01:06<00:00,  6.68s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:51<00:00, 58.30it/s]


MRR: 0.15
MR: 8785.17
Hits@10: 0.24
Hits@3: 0.17
Hits@1: 0.10
[54.20744498 68.34044049 80.38240956]


Average ComplEx Loss:   4.222802: 100%|██████████| 10/10 [01:04<00:00,  6.43s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:51<00:00, 58.23it/s]


MRR: 0.15
MR: 9310.53
Hits@10: 0.23
Hits@3: 0.17
Hits@1: 0.10
crossover c1: struct({'position': array([63.96758201, 68.55188423, 76.98138121]), 'cost': 0.14764479241124476})
crossover c2: struct({'position': array([54.20744498, 68.34044049, 80.38240956]), 'cost': 0.14778681999929597})
[ 66.97180008  46.64685601 100.        ]


Average ComplEx Loss:   3.828361: 100%|██████████| 10/10 [00:59<00:00,  5.97s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:07<00:00, 53.25it/s]


MRR: 0.16
MR: 8853.72
Hits@10: 0.25
Hits@3: 0.19
Hits@1: 0.12
[32.76846466 70.         93.76502235]


Average ComplEx Loss:   4.258890: 100%|██████████| 10/10 [01:25<00:00,  8.54s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:03<00:00, 54.37it/s]


MRR: 0.12
MR: 9443.99
Hits@10: 0.20
Hits@3: 0.14
Hits@1: 0.08
mutate c3: struct({'position': array([ 66.97180008,  46.64685601, 100.        ]), 'cost': 0.1646664809955003})
mutate c4: struct({'position': array([32.76846466, 70.        , 93.76502235]), 'cost': 0.12176115850181475})
P1: struct({'position': array([51.47704488, 53.30424993, 73.61647217]), 'cost': 0.13884218434809417})
P2: struct({'position': array([51.47704488, 53.30424993, 73.61647217]), 'cost': 0.13884218434809417})
Dynamic Programming
Dynamic Programming
crossover c1: struct({'position': array([51.47704488, 53.30424993, 73.61647217]), 'cost': 0.13884218434809417})
crossover c2: struct({'position': array([51.47704488, 53.30424993, 73.61647217]), 'cost': 0.13884218434809417})
[30.         70.         73.42136643]


Average ComplEx Loss:   4.260117: 100%|██████████| 10/10 [01:07<00:00,  6.80s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:52<00:00, 58.10it/s]


MRR: 0.10
MR: 9949.05
Hits@10: 0.17
Hits@3: 0.11
Hits@1: 0.07
[41.41962017 55.59732712 62.61247941]


Average ComplEx Loss:   4.020770: 100%|██████████| 10/10 [00:46<00:00,  4.60s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:44<00:00, 60.93it/s]


MRR: 0.11
MR: 9952.56
Hits@10: 0.19
Hits@3: 0.13
Hits@1: 0.07
mutate c3: struct({'position': array([30.        , 70.        , 73.42136643]), 'cost': 0.10081666662526856})
mutate c4: struct({'position': array([41.41962017, 55.59732712, 62.61247941]), 'cost': 0.1116961504321679})
pop: [struct({'position': array([ 66.97180008,  46.64685601, 100.        ]), 'cost': 0.1646664809955003}), struct({'position': array([71.82698769, 70.        , 80.35115798]), 'cost': 0.15680229017783076}), struct({'position': array([54.20744498, 68.34044049, 80.38240956]), 'cost': 0.14778681999929597})]
Iteration 2: Best Cost = 0.1646664809955003
P1: struct({'position': array([71.82698769, 70.        , 80.35115798]), 'cost': 0.15680229017783076})
P2: struct({'position': array([71.82698769, 70.        , 80.35115798]), 'cost': 0.15680229017783076})
Dynamic Programming
Dynamic Programming
crossover c1: struct({'position': array([71.82698769, 70.        , 80.35115798]), 'cost': 0.15680229017783076})
crossover c2: st

Average ComplEx Loss:   4.252910: 100%|██████████| 10/10 [01:03<00:00,  6.32s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:48<00:00, 59.36it/s]


MRR: 0.12
MR: 9813.35
Hits@10: 0.20
Hits@3: 0.14
Hits@1: 0.08
[49.44322873 70.         97.00267297]


Average ComplEx Loss:   4.252055: 100%|██████████| 10/10 [01:28<00:00,  8.85s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:07<00:00, 53.20it/s]


MRR: 0.15
MR: 8678.83
Hits@10: 0.24
Hits@3: 0.17
Hits@1: 0.11
mutate c3: struct({'position': array([55.61370086, 70.        , 67.61021506]), 'cost': 0.12122527705663047})
mutate c4: struct({'position': array([49.44322873, 70.        , 97.00267297]), 'cost': 0.15296908215976654})
P1: struct({'position': array([ 66.97180008,  46.64685601, 100.        ]), 'cost': 0.1646664809955003})
P2: struct({'position': array([71.82698769, 70.        , 80.35115798]), 'cost': 0.15680229017783076})
[70.10678965 57.11406078 81.22548112]


Average ComplEx Loss:   4.038241: 100%|██████████| 10/10 [01:01<00:00,  6.17s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:58<00:00, 56.15it/s]


MRR: 0.16
MR: 9268.93
Hits@10: 0.25
Hits@3: 0.19
Hits@1: 0.11
[68.69199813 59.53279523 99.12567686]


Average ComplEx Loss:   4.070752: 100%|██████████| 10/10 [01:16<00:00,  7.64s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:09<00:00, 52.86it/s]


MRR: 0.17
MR: 9163.59
Hits@10: 0.26
Hits@3: 0.19
Hits@1: 0.12
crossover c1: struct({'position': array([70.10678965, 57.11406078, 81.22548112]), 'cost': 0.16094020719214822})
crossover c2: struct({'position': array([68.69199813, 59.53279523, 99.12567686]), 'cost': 0.16561410622635375})
[68.47522615 45.6730957  64.66791735]


Average ComplEx Loss:   3.812468: 100%|██████████| 10/10 [00:35<00:00,  3.53s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:41<00:00, 61.92it/s]


MRR: 0.14
MR: 9230.16
Hits@10: 0.22
Hits@3: 0.15
Hits@1: 0.09
[68.69199813 67.73651737 99.12567686]


Average ComplEx Loss:   4.195748: 100%|██████████| 10/10 [01:26<00:00,  8.66s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:05<00:00, 53.83it/s]


MRR: 0.17
MR: 9209.56
Hits@10: 0.25
Hits@3: 0.19
Hits@1: 0.12
mutate c3: struct({'position': array([68.47522615, 45.6730957 , 64.66791735]), 'cost': 0.13534943743863168})
mutate c4: struct({'position': array([68.69199813, 67.73651737, 99.12567686]), 'cost': 0.16526036903438618})
pop: [struct({'position': array([68.69199813, 59.53279523, 99.12567686]), 'cost': 0.16561410622635375}), struct({'position': array([68.69199813, 67.73651737, 99.12567686]), 'cost': 0.16526036903438618}), struct({'position': array([ 66.97180008,  46.64685601, 100.        ]), 'cost': 0.1646664809955003})]
Iteration 3: Best Cost = 0.16561410622635375
P1: struct({'position': array([ 66.97180008,  46.64685601, 100.        ]), 'cost': 0.1646664809955003})
P2: struct({'position': array([68.69199813, 67.73651737, 99.12567686]), 'cost': 0.16526036903438618})
[67.25328592 52.34908368 99.54354333]


Average ComplEx Loss:   3.947719: 100%|██████████| 10/10 [01:07<00:00,  6.76s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:07<00:00, 53.21it/s]


MRR: 0.17
MR: 9148.44
Hits@10: 0.26
Hits@3: 0.19
Hits@1: 0.12
[68.41051229 62.0342897  99.58213353]


Average ComplEx Loss:   4.119479: 100%|██████████| 10/10 [01:20<00:00,  8.02s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:08<00:00, 52.99it/s]


MRR: 0.17
MR: 9177.86
Hits@10: 0.25
Hits@3: 0.19
Hits@1: 0.12
crossover c1: struct({'position': array([67.25328592, 52.34908368, 99.54354333]), 'cost': 0.1658603235613395})
crossover c2: struct({'position': array([68.41051229, 62.0342897 , 99.58213353]), 'cost': 0.16532248309928374})
[ 79.09096708  39.17894099 100.        ]


Average ComplEx Loss:   3.654693: 100%|██████████| 10/10 [00:51<00:00,  5.18s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:07<00:00, 53.45it/s]


MRR: 0.17
MR: 8872.11
Hits@10: 0.26
Hits@3: 0.19
Hits@1: 0.12
[61.71155568 70.         77.2343907 ]


Average ComplEx Loss:   4.247765: 100%|██████████| 10/10 [01:10<00:00,  7.04s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:52<00:00, 57.85it/s]


MRR: 0.15
MR: 9249.25
Hits@10: 0.24
Hits@3: 0.17
Hits@1: 0.11
mutate c3: struct({'position': array([ 79.09096708,  39.17894099, 100.        ]), 'cost': 0.1709930900378015})
mutate c4: struct({'position': array([61.71155568, 70.        , 77.2343907 ]), 'cost': 0.15410000855064054})
P1: struct({'position': array([68.69199813, 59.53279523, 99.12567686]), 'cost': 0.16561410622635375})
P2: struct({'position': array([ 66.97180008,  46.64685601, 100.        ]), 'cost': 0.1646664809955003})
[68.40051823 47.96217769 99.83083087]


Average ComplEx Loss:   3.847907: 100%|██████████| 10/10 [01:01<00:00,  6.15s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:07<00:00, 53.42it/s]


MRR: 0.17
MR: 9109.50
Hits@10: 0.26
Hits@3: 0.19
Hits@1: 0.12
[67.26327998 58.21747355 99.29484599]


Average ComplEx Loss:   4.054834: 100%|██████████| 10/10 [01:15<00:00,  7.51s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:06<00:00, 53.64it/s]


MRR: 0.17
MR: 9154.61
Hits@10: 0.25
Hits@3: 0.19
Hits@1: 0.12
crossover c1: struct({'position': array([68.40051823, 47.96217769, 99.83083087]), 'cost': 0.16578020582894923})
crossover c2: struct({'position': array([67.26327998, 58.21747355, 99.29484599]), 'cost': 0.16524445562381535})
[89.95284869 34.1406443  99.83083087]


Average ComplEx Loss:   3.511742: 100%|██████████| 10/10 [00:46<00:00,  4.67s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:06<00:00, 53.51it/s]


MRR: 0.17
MR: 9045.72
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
[65.9924001  70.         96.45110987]


Average ComplEx Loss:   4.241847: 100%|██████████| 10/10 [01:16<00:00,  7.61s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:57<00:00, 56.18it/s]


MRR: 0.17
MR: 8354.92
Hits@10: 0.26
Hits@3: 0.18
Hits@1: 0.12
mutate c3: struct({'position': array([89.95284869, 34.1406443 , 99.83083087]), 'cost': 0.1729138772973974})
mutate c4: struct({'position': array([65.9924001 , 70.        , 96.45110987]), 'cost': 0.16630329523273052})
pop: [struct({'position': array([89.95284869, 34.1406443 , 99.83083087]), 'cost': 0.1729138772973974}), struct({'position': array([ 79.09096708,  39.17894099, 100.        ]), 'cost': 0.1709930900378015}), struct({'position': array([65.9924001 , 70.        , 96.45110987]), 'cost': 0.16630329523273052})]
Iteration 4: Best Cost = 0.1729138772973974
P1: struct({'position': array([89.95284869, 34.1406443 , 99.83083087]), 'cost': 0.1729138772973974})
P2: struct({'position': array([65.9924001 , 70.        , 96.45110987]), 'cost': 0.16630329523273052})
[80.97462517 47.54291196 97.56053106]


Average ComplEx Loss:   3.836775: 100%|██████████| 10/10 [01:00<00:00,  6.06s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:04<00:00, 54.09it/s]


MRR: 0.17
MR: 8649.30
Hits@10: 0.26
Hits@3: 0.20
Hits@1: 0.12
[74.97062363 56.59773234 98.72140967]


Average ComplEx Loss:   4.012001: 100%|██████████| 10/10 [01:10<00:00,  7.06s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:03<00:00, 54.56it/s]


MRR: 0.16
MR: 9055.03
Hits@10: 0.26
Hits@3: 0.19
Hits@1: 0.11
crossover c1: struct({'position': array([80.97462517, 47.54291196, 97.56053106]), 'cost': 0.17043751314437042})
crossover c2: struct({'position': array([74.97062363, 56.59773234, 98.72140967]), 'cost': 0.16266963628346534})
[97.96512354 70.         90.47313264]


Average ComplEx Loss:   4.212927: 100%|██████████| 10/10 [01:22<00:00,  8.30s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:01<00:00, 55.18it/s]


MRR: 0.17
MR: 8708.49
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
[74.97062363 41.75666278 98.72140967]


Average ComplEx Loss:   3.707217: 100%|██████████| 10/10 [00:52<00:00,  5.28s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:04<00:00, 54.34it/s]


MRR: 0.16
MR: 8951.33
Hits@10: 0.26
Hits@3: 0.19
Hits@1: 0.11
mutate c3: struct({'position': array([97.96512354, 70.        , 90.47313264]), 'cost': 0.17241856319095758})
mutate c4: struct({'position': array([74.97062363, 41.75666278, 98.72140967]), 'cost': 0.16364645706392245})
P1: struct({'position': array([89.95284869, 34.1406443 , 99.83083087]), 'cost': 0.1729138772973974})
P2: struct({'position': array([ 79.09096708,  39.17894099, 100.        ]), 'cost': 0.1709930900378015})
[88.75893817 38.6814769  99.87331775]


Average ComplEx Loss:   3.620749: 100%|██████████| 10/10 [00:51<00:00,  5.17s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:15<00:00, 51.02it/s]


MRR: 0.17
MR: 9080.92
Hits@10: 0.26
Hits@3: 0.20
Hits@1: 0.12
[80.28487761 34.6381084  99.95751311]


Average ComplEx Loss:   3.521737: 100%|██████████| 10/10 [00:46<00:00,  4.62s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:09<00:00, 52.71it/s]


MRR: 0.17
MR: 9037.86
Hits@10: 0.26
Hits@3: 0.19
Hits@1: 0.12
crossover c1: struct({'position': array([88.75893817, 38.6814769 , 99.87331775]), 'cost': 0.17289455043505678})
crossover c2: struct({'position': array([80.28487761, 34.6381084 , 99.95751311]), 'cost': 0.1712027099233502})
[73.90054652 29.63280636 86.46068838]


Average ComplEx Loss:   3.376985: 100%|██████████| 10/10 [00:35<00:00,  3.54s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:03<00:00, 54.64it/s]


MRR: 0.17
MR: 8832.81
Hits@10: 0.26
Hits@3: 0.19
Hits@1: 0.12
[100.          40.06205912  99.95751311]


Average ComplEx Loss:   3.655055: 100%|██████████| 10/10 [00:54<00:00,  5.48s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:07<00:00, 53.29it/s]


MRR: 0.17
MR: 9156.42
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
mutate c3: struct({'position': array([73.90054652, 29.63280636, 86.46068838]), 'cost': 0.16964524654998395})
mutate c4: struct({'position': array([100.        ,  40.06205912,  99.95751311]), 'cost': 0.17368344402761837})
pop: [struct({'position': array([100.        ,  40.06205912,  99.95751311]), 'cost': 0.17368344402761837}), struct({'position': array([89.95284869, 34.1406443 , 99.83083087]), 'cost': 0.1729138772973974}), struct({'position': array([88.75893817, 38.6814769 , 99.87331775]), 'cost': 0.17289455043505678})]
Iteration 5: Best Cost = 0.17368344402761837
P1: struct({'position': array([88.75893817, 38.6814769 , 99.87331775]), 'cost': 0.17289455043505678})
P2: struct({'position': array([89.95284869, 34.1406443 , 99.83083087]), 'cost': 0.1729138772973974})
[88.95720128 35.40068221 99.8425956 ]


Average ComplEx Loss:   3.540940: 100%|██████████| 10/10 [00:47<00:00,  4.78s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:10<00:00, 52.53it/s]


MRR: 0.17
MR: 9076.89
Hits@10: 0.26
Hits@3: 0.20
Hits@1: 0.12
[89.75458558 37.42143899 99.86155302]


Average ComplEx Loss:   3.593738: 100%|██████████| 10/10 [00:50<00:00,  5.03s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:09<00:00, 52.86it/s]


MRR: 0.17
MR: 9084.75
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
crossover c1: struct({'position': array([88.95720128, 35.40068221, 99.8425956 ]), 'cost': 0.17261617706430096})
crossover c2: struct({'position': array([89.75458558, 37.42143899, 99.86155302]), 'cost': 0.17245115642741735})
[61.89132419 35.40068221 97.08983314]


Average ComplEx Loss:   3.566066: 100%|██████████| 10/10 [00:45<00:00,  4.59s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:07<00:00, 53.46it/s]


MRR: 0.16
MR: 8471.01
Hits@10: 0.26
Hits@3: 0.19
Hits@1: 0.11
[100.          37.42143899 100.        ]


Average ComplEx Loss:   3.577917: 100%|██████████| 10/10 [00:50<00:00,  5.04s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:08<00:00, 53.11it/s]


MRR: 0.17
MR: 8971.61
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
mutate c3: struct({'position': array([61.89132419, 35.40068221, 97.08983314]), 'cost': 0.16422381296780397})
mutate c4: struct({'position': array([100.        ,  37.42143899, 100.        ]), 'cost': 0.1733210187724959})
P1: struct({'position': array([89.95284869, 34.1406443 , 99.83083087]), 'cost': 0.1729138772973974})
P2: struct({'position': array([89.95284869, 34.1406443 , 99.83083087]), 'cost': 0.1729138772973974})
Dynamic Programming
Dynamic Programming
crossover c1: struct({'position': array([89.95284869, 34.1406443 , 99.83083087]), 'cost': 0.1729138772973974})
crossover c2: struct({'position': array([89.95284869, 34.1406443 , 99.83083087]), 'cost': 0.1729138772973974})
[100.          56.91280631 100.        ]


Average ComplEx Loss:   3.981969: 100%|██████████| 10/10 [01:13<00:00,  7.32s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:08<00:00, 52.91it/s]


MRR: 0.17
MR: 9125.05
Hits@10: 0.26
Hits@3: 0.20
Hits@1: 0.12
[90.00453023 33.87115995 63.06147949]


Average ComplEx Loss:   3.496531: 100%|██████████| 10/10 [00:30<00:00,  3.05s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:45<00:00, 60.25it/s]


MRR: 0.14
MR: 9216.37
Hits@10: 0.24
Hits@3: 0.17
Hits@1: 0.10
mutate c3: struct({'position': array([100.        ,  56.91280631, 100.        ]), 'cost': 0.17273631041013693})
mutate c4: struct({'position': array([90.00453023, 33.87115995, 63.06147949]), 'cost': 0.14495639556116482})
pop: [struct({'position': array([100.        ,  40.06205912,  99.95751311]), 'cost': 0.17368344402761837}), struct({'position': array([100.        ,  37.42143899, 100.        ]), 'cost': 0.1733210187724959}), struct({'position': array([89.95284869, 34.1406443 , 99.83083087]), 'cost': 0.1729138772973974})]
Iteration 6: Best Cost = 0.17368344402761837
P1: struct({'position': array([100.        ,  37.42143899, 100.        ]), 'cost': 0.1733210187724959})
P2: struct({'position': array([100.        ,  37.42143899, 100.        ]), 'cost': 0.1733210187724959})
Dynamic Programming
Dynamic Programming
crossover c1: struct({'position': array([100.        ,  37.42143899, 100.        ]), 'cost': 0.1733210187724959})
cro

Average ComplEx Loss:   3.435204: 100%|██████████| 10/10 [00:35<00:00,  3.54s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:56<00:00, 56.68it/s]


MRR: 0.16
MR: 9188.54
Hits@10: 0.25
Hits@3: 0.18
Hits@1: 0.11
[100.          37.42143899  98.4955318 ]


Average ComplEx Loss:   3.574733: 100%|██████████| 10/10 [00:49<00:00,  4.92s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:06<00:00, 53.58it/s]


MRR: 0.17
MR: 9079.38
Hits@10: 0.26
Hits@3: 0.19
Hits@1: 0.12
mutate c3: struct({'position': array([85.07852534, 31.21786543, 79.20438632]), 'cost': 0.15685847003282197})
mutate c4: struct({'position': array([100.        ,  37.42143899,  98.4955318 ]), 'cost': 0.16864991203043517})
P1: struct({'position': array([89.95284869, 34.1406443 , 99.83083087]), 'cost': 0.1729138772973974})
P2: struct({'position': array([100.        ,  37.42143899, 100.        ]), 'cost': 0.1733210187724959})
[97.26418409 34.61096655 99.87606644]


Average ComplEx Loss:   3.501840: 100%|██████████| 10/10 [00:47<00:00,  4.71s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:10<00:00, 52.42it/s]


MRR: 0.17
MR: 9093.71
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
[92.6886646  36.95111674 99.95476442]


Average ComplEx Loss:   3.563317: 100%|██████████| 10/10 [00:49<00:00,  4.95s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:10<00:00, 52.53it/s]


MRR: 0.17
MR: 9081.94
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
crossover c1: struct({'position': array([97.26418409, 34.61096655, 99.87606644]), 'cost': 0.174452772331595})
crossover c2: struct({'position': array([92.6886646 , 36.95111674, 99.95476442]), 'cost': 0.17420175227557747})
[78.64459066 62.63527777 88.92232411]


Average ComplEx Loss:   4.112948: 100%|██████████| 10/10 [01:07<00:00,  6.78s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:59<00:00, 55.71it/s]


MRR: 0.17
MR: 9026.20
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
[86.10047755 27.58429027 98.17312096]


Average ComplEx Loss:   3.289625: 100%|██████████| 10/10 [00:37<00:00,  3.75s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:07<00:00, 53.19it/s]


MRR: 0.17
MR: 8865.36
Hits@10: 0.26
Hits@3: 0.19
Hits@1: 0.12
mutate c3: struct({'position': array([78.64459066, 62.63527777, 88.92232411]), 'cost': 0.17265427244347883})
mutate c4: struct({'position': array([86.10047755, 27.58429027, 98.17312096]), 'cost': 0.16747040124339957})
pop: [struct({'position': array([97.26418409, 34.61096655, 99.87606644]), 'cost': 0.174452772331595}), struct({'position': array([92.6886646 , 36.95111674, 99.95476442]), 'cost': 0.17420175227557747}), struct({'position': array([100.        ,  40.06205912,  99.95751311]), 'cost': 0.17368344402761837})]
Iteration 7: Best Cost = 0.174452772331595
P1: struct({'position': array([92.6886646 , 36.95111674, 99.95476442]), 'cost': 0.17420175227557747})
P2: struct({'position': array([92.6886646 , 36.95111674, 99.95476442]), 'cost': 0.17420175227557747})
Dynamic Programming
Dynamic Programming
crossover c1: struct({'position': array([92.6886646 , 36.95111674, 99.95476442]), 'cost': 0.17420175227557747})
crossover c2: str

Average ComplEx Loss:   2.987974: 100%|██████████| 10/10 [00:30<00:00,  3.06s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:10<00:00, 52.47it/s]


MRR: 0.18
MR: 8754.64
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
[100.          36.95111674  98.41509586]


Average ComplEx Loss:   3.548177: 100%|██████████| 10/10 [00:48<00:00,  4.82s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:07<00:00, 53.31it/s]


MRR: 0.17
MR: 9087.14
Hits@10: 0.26
Hits@3: 0.19
Hits@1: 0.12
mutate c3: struct({'position': array([100.,  20., 100.]), 'cost': 0.17603006275816038})
mutate c4: struct({'position': array([100.        ,  36.95111674,  98.41509586]), 'cost': 0.16829312601977248})
P1: struct({'position': array([92.6886646 , 36.95111674, 99.95476442]), 'cost': 0.17420175227557747})
P2: struct({'position': array([97.26418409, 34.61096655, 99.87606644]), 'cost': 0.174452772331595})
[93.80372368 34.93088272 99.89643454]


Average ComplEx Loss:   3.506838: 100%|██████████| 10/10 [00:46<00:00,  4.69s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:10<00:00, 52.56it/s]


MRR: 0.17
MR: 9064.68
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
[96.14912502 36.63120057 99.93439633]


Average ComplEx Loss:   3.557823: 100%|██████████| 10/10 [00:49<00:00,  4.95s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:08<00:00, 52.91it/s]


MRR: 0.17
MR: 9103.93
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
crossover c1: struct({'position': array([93.80372368, 34.93088272, 99.89643454]), 'cost': 0.17390130471988044})
crossover c2: struct({'position': array([96.14912502, 36.63120057, 99.93439633]), 'cost': 0.17388612128413347})
[100.          27.68048444  98.84033892]


Average ComplEx Loss:   3.270822: 100%|██████████| 10/10 [00:38<00:00,  3.84s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:06<00:00, 53.72it/s]


MRR: 0.17
MR: 8970.46
Hits@10: 0.26
Hits@3: 0.19
Hits@1: 0.12
[98.12331963 21.92627372 97.32488976]


Average ComplEx Loss:   3.038233: 100%|██████████| 10/10 [00:31<00:00,  3.12s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:07<00:00, 53.21it/s]


MRR: 0.17
MR: 8491.66
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
mutate c3: struct({'position': array([100.        ,  27.68048444,  98.84033892]), 'cost': 0.16945077405656342})
mutate c4: struct({'position': array([98.12331963, 21.92627372, 97.32488976]), 'cost': 0.17471766713454565})
pop: [struct({'position': array([100.,  20., 100.]), 'cost': 0.17603006275816038}), struct({'position': array([98.12331963, 21.92627372, 97.32488976]), 'cost': 0.17471766713454565}), struct({'position': array([97.26418409, 34.61096655, 99.87606644]), 'cost': 0.174452772331595})]
Iteration 8: Best Cost = 0.17603006275816038
P1: struct({'position': array([100.,  20., 100.]), 'cost': 0.17603006275816038})
P2: struct({'position': array([98.12331963, 21.92627372, 97.32488976]), 'cost': 0.17471766713454565})
[98.69368157 20.25736723 97.79494615]


Average ComplEx Loss:   2.991995: 100%|██████████| 10/10 [00:29<00:00,  3.00s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:07<00:00, 53.33it/s]


MRR: 0.17
MR: 8492.93
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
[99.42963806 21.66890649 99.52994361]


Average ComplEx Loss:   3.036591: 100%|██████████| 10/10 [00:31<00:00,  3.18s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:08<00:00, 53.09it/s]


MRR: 0.18
MR: 8957.48
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.13
crossover c1: struct({'position': array([98.69368157, 20.25736723, 97.79494615]), 'cost': 0.1746481632384747})
crossover c2: struct({'position': array([99.42963806, 21.66890649, 99.52994361]), 'cost': 0.17543799636156795})
[ 82.30350092  20.         100.        ]


Average ComplEx Loss:   3.009683: 100%|██████████| 10/10 [00:29<00:00,  2.97s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:04<00:00, 54.06it/s]


MRR: 0.17
MR: 8695.46
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
[100.          20.77541077 100.        ]


Average ComplEx Loss:   2.987974: 100%|██████████| 10/10 [00:30<00:00,  3.06s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:03<00:00, 54.35it/s]


MRR: 0.18
MR: 8754.64
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
mutate c3: struct({'position': array([ 82.30350092,  20.        , 100.        ]), 'cost': 0.1718387642026156})
mutate c4: struct({'position': array([100.        ,  20.77541077, 100.        ]), 'cost': 0.17603006274714067})
P1: struct({'position': array([100.,  20., 100.]), 'cost': 0.17603006275816038})
P2: struct({'position': array([98.12331963, 21.92627372, 97.32488976]), 'cost': 0.17471766713454565})
[98.64420866 21.55046306 99.90502483]


Average ComplEx Loss:   3.038125: 100%|██████████| 10/10 [00:31<00:00,  3.16s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:04<00:00, 54.06it/s]


MRR: 0.17
MR: 8984.32
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
[99.47911097 20.37581066 97.41986493]


Average ComplEx Loss:   2.990449: 100%|██████████| 10/10 [00:30<00:00,  3.02s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:03<00:00, 54.38it/s]


MRR: 0.18
MR: 8477.71
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
crossover c1: struct({'position': array([98.64420866, 21.55046306, 99.90502483]), 'cost': 0.17430692447383422})
crossover c2: struct({'position': array([99.47911097, 20.37581066, 97.41986493]), 'cost': 0.17524133629459454})
[ 84.91144047  34.71344886 100.        ]


Average ComplEx Loss:   3.516532: 100%|██████████| 10/10 [00:45<00:00,  4.58s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:06<00:00, 53.60it/s]


MRR: 0.17
MR: 8843.86
Hits@10: 0.26
Hits@3: 0.20
Hits@1: 0.12
[100.          20.          86.58336408]


Average ComplEx Loss:   2.994452: 100%|██████████| 10/10 [00:27<00:00,  2.70s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:55<00:00, 56.86it/s]


MRR: 0.18
MR: 8816.20
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.13
mutate c3: struct({'position': array([ 84.91144047,  34.71344886, 100.        ]), 'cost': 0.17188173764753473})
mutate c4: struct({'position': array([100.        ,  20.        ,  86.58336408]), 'cost': 0.17797409749458262})
pop: [struct({'position': array([100.        ,  20.        ,  86.58336408]), 'cost': 0.17797409749458262}), struct({'position': array([100.,  20., 100.]), 'cost': 0.17603006275816038}), struct({'position': array([100.        ,  20.77541077, 100.        ]), 'cost': 0.17603006274714067})]
Iteration 9: Best Cost = 0.17797409749458262
P1: struct({'position': array([100.,  20., 100.]), 'cost': 0.17603006275816038})
P2: struct({'position': array([100.        ,  20.        ,  86.58336408]), 'cost': 0.17797409749458262})
[100.          20.          87.03326652]


Average ComplEx Loss:   2.994288: 100%|██████████| 10/10 [00:27<00:00,  2.75s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:58<00:00, 56.02it/s]


MRR: 0.18
MR: 8658.98
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.13
[100.          20.          99.55009756]


Average ComplEx Loss:   2.989318: 100%|██████████| 10/10 [00:30<00:00,  3.05s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:05<00:00, 53.82it/s]


MRR: 0.17
MR: 8940.29
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
crossover c1: struct({'position': array([100.        ,  20.        ,  87.03326652]), 'cost': 0.17883087134197845})
crossover c2: struct({'position': array([100.        ,  20.        ,  99.55009756]), 'cost': 0.17440670130946606})
[72.23681233 20.         94.83428493]


Average ComplEx Loss:   3.020998: 100%|██████████| 10/10 [00:27<00:00,  2.77s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:01<00:00, 55.07it/s]


MRR: 0.17
MR: 8480.65
Hits@10: 0.27
Hits@3: 0.19
Hits@1: 0.12
[100.          48.56766901  92.19409459]


Average ComplEx Loss:   3.836026: 100%|██████████| 10/10 [00:59<00:00,  5.91s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:00<00:00, 55.31it/s]


MRR: 0.17
MR: 9144.64
Hits@10: 0.26
Hits@3: 0.20
Hits@1: 0.12
mutate c3: struct({'position': array([72.23681233, 20.        , 94.83428493]), 'cost': 0.16957869443800763})
mutate c4: struct({'position': array([100.        ,  48.56766901,  92.19409459]), 'cost': 0.17110822962243488})
P1: struct({'position': array([100.        ,  20.77541077, 100.        ]), 'cost': 0.17603006274714067})
P2: struct({'position': array([100.        ,  20.        ,  86.58336408]), 'cost': 0.17797409749458262})
[100.          20.54203552  92.60135243]


Average ComplEx Loss:   2.992353: 100%|██████████| 10/10 [00:28<00:00,  2.85s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:59<00:00, 55.63it/s]


MRR: 0.17
MR: 8858.13
Hits@10: 0.26
Hits@3: 0.20
Hits@1: 0.12
[100.          20.23337525  93.98201164]


Average ComplEx Loss:   2.992566: 100%|██████████| 10/10 [00:29<00:00,  2.92s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:01<00:00, 55.23it/s]


MRR: 0.17
MR: 8641.85
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
crossover c1: struct({'position': array([100.        ,  20.54203552,  92.60135243]), 'cost': 0.17345423335143922})
crossover c2: struct({'position': array([100.        ,  20.23337525,  93.98201164]), 'cost': 0.17400194231451865})
[100.          20.          89.09894588]


Average ComplEx Loss:   2.994784: 100%|██████████| 10/10 [00:27<00:00,  2.79s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:58<00:00, 55.89it/s]


MRR: 0.18
MR: 8771.58
Hits@10: 0.28
Hits@3: 0.20
Hits@1: 0.13
[100.          20.          72.55889554]


Average ComplEx Loss:   3.004849: 100%|██████████| 10/10 [00:22<00:00,  2.27s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:50<00:00, 58.61it/s]


MRR: 0.15
MR: 9127.01
Hits@10: 0.24
Hits@3: 0.17
Hits@1: 0.11
mutate c3: struct({'position': array([100.        ,  20.        ,  89.09894588]), 'cost': 0.17928294641348488})
mutate c4: struct({'position': array([100.        ,  20.        ,  72.55889554]), 'cost': 0.1530766055763642})
pop: [struct({'position': array([100.        ,  20.        ,  89.09894588]), 'cost': 0.17928294641348488}), struct({'position': array([100.        ,  20.        ,  87.03326652]), 'cost': 0.17883087134197845}), struct({'position': array([100.        ,  20.        ,  86.58336408]), 'cost': 0.17797409749458262})]
Iteration 10: Best Cost = 0.17928294641348488
P1: struct({'position': array([100.        ,  20.        ,  89.09894588]), 'cost': 0.17928294641348488})
P2: struct({'position': array([100.        ,  20.        ,  87.03326652]), 'cost': 0.17883087134197845})
[100.          20.          87.42645226]


Average ComplEx Loss:   2.994288: 100%|██████████| 10/10 [00:27<00:00,  2.79s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:03<00:00, 54.64it/s]


MRR: 0.18
MR: 8658.98
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.13
[100.          20.          88.70576014]


Average ComplEx Loss:   2.994323: 100%|██████████| 10/10 [00:26<00:00,  2.69s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:55<00:00, 57.05it/s]


MRR: 0.18
MR: 8829.95
Hits@10: 0.28
Hits@3: 0.20
Hits@1: 0.12
crossover c1: struct({'position': array([100.        ,  20.        ,  87.42645226]), 'cost': 0.17883087113631388})
crossover c2: struct({'position': array([100.        ,  20.        ,  88.70576014]), 'cost': 0.1769983785306107})
[100.          20.          58.19335232]


Average ComplEx Loss:   3.009287: 100%|██████████| 10/10 [00:19<00:00,  1.95s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:41<00:00, 62.00it/s]


MRR: 0.15
MR: 9113.28
Hits@10: 0.24
Hits@3: 0.17
Hits@1: 0.10
[99.32264512 20.         97.32236703]


Average ComplEx Loss:   2.990449: 100%|██████████| 10/10 [00:30<00:00,  3.02s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:04<00:00, 54.34it/s]


MRR: 0.18
MR: 8477.71
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
mutate c3: struct({'position': array([100.        ,  20.        ,  58.19335232]), 'cost': 0.14543286971030883})
mutate c4: struct({'position': array([99.32264512, 20.        , 97.32236703]), 'cost': 0.17524133628796626})
P1: struct({'position': array([100.        ,  20.        ,  86.58336408]), 'cost': 0.17797409749458262})
P2: struct({'position': array([100.        ,  20.        ,  87.03326652]), 'cost': 0.17883087134197845})
[100.          20.          86.87519368]


Average ComplEx Loss:   2.994452: 100%|██████████| 10/10 [00:27<00:00,  2.72s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:56<00:00, 56.55it/s]


MRR: 0.18
MR: 8816.20
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.13
[100.          20.          86.74143691]


Average ComplEx Loss:   2.994452: 100%|██████████| 10/10 [00:26<00:00,  2.70s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:57<00:00, 56.41it/s]


MRR: 0.18
MR: 8816.20
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.13
crossover c1: struct({'position': array([100.        ,  20.        ,  86.87519368]), 'cost': 0.1779740974827047})
crossover c2: struct({'position': array([100.        ,  20.        ,  86.74143691]), 'cost': 0.17797409748839102})
[65.69227536 20.         53.85802716]


Average ComplEx Loss:   3.033397: 100%|██████████| 10/10 [00:16<00:00,  1.70s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:39<00:00, 62.58it/s]


MRR: 0.13
MR: 9232.03
Hits@10: 0.21
Hits@3: 0.14
Hits@1: 0.09
[95.01905642 20.         60.32201036]


Average ComplEx Loss:   3.013067: 100%|██████████| 10/10 [00:19<00:00,  1.97s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:41<00:00, 61.77it/s]


MRR: 0.14
MR: 9949.00
Hits@10: 0.23
Hits@3: 0.16
Hits@1: 0.09
mutate c3: struct({'position': array([65.69227536, 20.        , 53.85802716]), 'cost': 0.12768011717080752})
mutate c4: struct({'position': array([95.01905642, 20.        , 60.32201036]), 'cost': 0.1403785333510305})
pop: [struct({'position': array([100.        ,  20.        ,  89.09894588]), 'cost': 0.17928294641348488}), struct({'position': array([100.        ,  20.        ,  87.03326652]), 'cost': 0.17883087134197845}), struct({'position': array([100.        ,  20.        ,  87.42645226]), 'cost': 0.17883087113631388})]
Iteration 11: Best Cost = 0.17928294641348488
P1: struct({'position': array([100.        ,  20.        ,  89.09894588]), 'cost': 0.17928294641348488})
P2: struct({'position': array([100.        ,  20.        ,  87.03326652]), 'cost': 0.17883087134197845})
[100.          20.          88.75935341]


Average ComplEx Loss:   2.994323: 100%|██████████| 10/10 [00:26<00:00,  2.68s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:54<00:00, 57.24it/s]


MRR: 0.18
MR: 8829.95
Hits@10: 0.28
Hits@3: 0.20
Hits@1: 0.12
[100.          20.          87.37285899]


Average ComplEx Loss:   2.994288: 100%|██████████| 10/10 [00:27<00:00,  2.74s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:58<00:00, 55.97it/s]


MRR: 0.18
MR: 8658.98
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.13
crossover c1: struct({'position': array([100.        ,  20.        ,  88.75935341]), 'cost': 0.17699837852890374})
crossover c2: struct({'position': array([100.        ,  20.        ,  87.37285899]), 'cost': 0.17883087105640608})
[93.66033122 24.45649755 60.70028728]


Average ComplEx Loss:   3.188847: 100%|██████████| 10/10 [00:22<00:00,  2.27s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:42<00:00, 61.56it/s]


MRR: 0.14
MR: 9994.60
Hits@10: 0.22
Hits@3: 0.16
Hits@1: 0.09
[94.56617512 20.         84.86106113]


Average ComplEx Loss:   3.004106: 100%|██████████| 10/10 [00:25<00:00,  2.58s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:54<00:00, 57.25it/s]


MRR: 0.17
MR: 8789.92
Hits@10: 0.26
Hits@3: 0.19
Hits@1: 0.12
mutate c3: struct({'position': array([93.66033122, 24.45649755, 60.70028728]), 'cost': 0.13914412696425577})
mutate c4: struct({'position': array([94.56617512, 20.        , 84.86106113]), 'cost': 0.16557916546700002})
P1: struct({'position': array([100.        ,  20.        ,  87.03326652]), 'cost': 0.17883087134197845})
P2: struct({'position': array([100.        ,  20.        ,  87.42645226]), 'cost': 0.17883087113631388})
[100.          20.          87.39066072]


Average ComplEx Loss:   2.994288: 100%|██████████| 10/10 [00:27<00:00,  2.75s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:00<00:00, 55.53it/s]


MRR: 0.18
MR: 8658.98
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.13
[100.          20.          87.06905805]


Average ComplEx Loss:   2.994288: 100%|██████████| 10/10 [00:27<00:00,  2.76s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:58<00:00, 55.99it/s]


MRR: 0.18
MR: 8658.98
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.13
crossover c1: struct({'position': array([100.        ,  20.        ,  87.39066072]), 'cost': 0.17883087135892722})
crossover c2: struct({'position': array([100.        ,  20.        ,  87.06905805]), 'cost': 0.17883087140583523})
[100.          20.          78.71336079]


Average ComplEx Loss:   2.999436: 100%|██████████| 10/10 [00:24<00:00,  2.50s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:51<00:00, 58.25it/s]


MRR: 0.17
MR: 8882.42
Hits@10: 0.26
Hits@3: 0.19
Hits@1: 0.12
[89.72464314 20.         85.77495985]


Average ComplEx Loss:   3.007933: 100%|██████████| 10/10 [00:26<00:00,  2.62s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:58<00:00, 56.01it/s]


MRR: 0.17
MR: 8709.63
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
mutate c3: struct({'position': array([100.        ,  20.        ,  78.71336079]), 'cost': 0.16570951086086205})
mutate c4: struct({'position': array([89.72464314, 20.        , 85.77495985]), 'cost': 0.17388479199466864})
pop: [struct({'position': array([100.        ,  20.        ,  89.09894588]), 'cost': 0.17928294641348488}), struct({'position': array([100.        ,  20.        ,  87.06905805]), 'cost': 0.17883087140583523}), struct({'position': array([100.        ,  20.        ,  87.39066072]), 'cost': 0.17883087135892722})]
Iteration 12: Best Cost = 0.17928294641348488
P1: struct({'position': array([100.        ,  20.        ,  87.06905805]), 'cost': 0.17883087140583523})
P2: struct({'position': array([100.        ,  20.        ,  89.09894588]), 'cost': 0.17928294641348488})
[100.          20.          87.28620632]


Average ComplEx Loss:   2.994288: 100%|██████████| 10/10 [00:27<00:00,  2.78s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:59<00:00, 55.67it/s]


MRR: 0.18
MR: 8658.98
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.13
[100.          20.          88.88179761]


Average ComplEx Loss:   2.994323: 100%|██████████| 10/10 [00:26<00:00,  2.66s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [02:55<00:00, 56.94it/s]


MRR: 0.18
MR: 8829.95
Hits@10: 0.28
Hits@3: 0.20
Hits@1: 0.12
crossover c1: struct({'position': array([100.        ,  20.        ,  87.28620632]), 'cost': 0.17883087135869358})
crossover c2: struct({'position': array([100.        ,  20.        ,  88.88179761]), 'cost': 0.17699838203802848})
[100.          25.45086156 100.        ]


Average ComplEx Loss:   3.200218: 100%|██████████| 10/10 [00:36<00:00,  3.66s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



100%|██████████| 10000/10000 [03:06<00:00, 53.55it/s]


MRR: 0.17
MR: 8830.14
Hits@10: 0.27
Hits@3: 0.20
Hits@1: 0.12
[100.          20.          83.65418194]


Average ComplEx Loss:   2.997627: 100%|██████████| 10/10 [00:26<00:00,  2.64s/epoch]

WARNING - DeprecationWarning: use_default_protocol will be removed in future. Please use corrupt_side argument instead.



 64%|██████▍   | 6441/10000 [01:51<01:01, 57.75it/s]

In [2]:
df = pd.DataFrame({"position": [bestSolution[0].position] , "cost": [bestSolution[0].cost]})
for i in range(params.maxit):
    if(i==0):
        continue;
    df.loc[len(df.index)] = [bestSolution[i].position , bestSolution[i].cost] 
df.to_excel('result.xlsx')
df